In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('datasets/coca-cola_from_dump.csv')

In [4]:
df

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g
0,22222084941,Coca-Cola original,Coca-Cola,"beverages, carbonated-drinks, sodas, colas",spain,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
1,42111558865,coca cola zéro,"Coca-Cola-light, coca cola","beverages, carbonated-drinks, artificially-swe...",france,"plastic, bottle",NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
2,49000004632,Coca-Cola,Coca-Cola,"beverages-and-beverages-preparations, beverage...","france, united-states","bottle-or-vial, bottle",NaN,NaN,e,4.0,NaN,"CARBONATED WATER, CANE SUGAR, CARAMEL COLOR, P...",NaN,NaN
3,49000012781,Coca-Cola,Coca-Cola,NaN,united-states,NaN,NaN,NaN,unknown,4.0,NaN,"CARBONATED WATER, HIGH FRUCTOSE CORN SYRUP, CA...",11.0,39.4
4,49000024685,Original Taste Soda,Coca-Cola,"beverages-and-beverages-preparations, beverage...","france, united-states",NaN,NaN,NaN,e,4.0,NaN,caffeiedo amount/serving % daily value nutriti...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4984,5000112686692,NaN,Coca Cola,"beverages-and-beverages-preparations, beverage...",germany,NaN,NaN,NaN,b,NaN,NaN,"água, dióxido de carbono, sumo de lima proveni...",NaN,NaN
4985,6990871421605,Coca Cola Coca Cola,Coca Cola,Dagligvarer,denmark,NaN,NaN,NaN,unknown,4.0,NaN,"Vand, sukker, kuldioxid, farvestof (E150d), sy...",NaN,NaN
4986,5942321005454,Coke zero zero,Coca-Cola,NaN,romania,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
4987,49000056166,Cherry Float Coke Zero,Coca-Cola,NaN,united-states,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
4988,7801610350652,Coca-Cola Zero Azucar,Coca-Cola,"beverages-and-beverages-preparations, beverage...","argentina, bolivia, brazil, chile, guatemala, ...",NaN,NaN,NaN,c,4.0,NaN,"Agua carbonatada, color caramelo, ácido fosfór...",NaN,NaN

In [5]:
df.tail()

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g
4984,5000112686692,NaN,Coca Cola,"beverages-and-beverages-preparations, beverage...",germany,NaN,NaN,NaN,b,NaN,NaN,"água, dióxido de carbono, sumo de lima proveni...",NaN,NaN
4985,6990871421605,Coca Cola Coca Cola,Coca Cola,Dagligvarer,denmark,NaN,NaN,NaN,unknown,4.0,NaN,"Vand, sukker, kuldioxid, farvestof (E150d), sy...",NaN,NaN
4986,5942321005454,Coke zero zero,Coca-Cola,NaN,romania,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
4987,49000056166,Cherry Float Coke Zero,Coca-Cola,NaN,united-states,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
4988,7801610350652,Coca-Cola Zero Azucar,Coca-Cola,"beverages-and-beverages-preparations, beverage...","argentina, bolivia, brazil, chile, guatemala, ...",NaN,NaN,NaN,c,4.0,NaN,"Agua carbonatada, color caramelo, ácido fosfór...",NaN,NaN

In [6]:
df.isnull().sum()

code                              0
product_name                    260
brands                          389
categories_tags                1954
countries_tags                   28
packaging_tags                 3721
stores                         4429
purchase_places                4449
nutriscore_grade                  1
nova_group                     3084
ecoscore_grade                 4249
ingredients_text               2741
nutriments.sugars_100g         3990
nutriments.energy-kcal_100g    3940
dtype: int64

In [7]:
df.dtypes

code                            object
product_name                       str
brands                             str
categories_tags                    str
countries_tags                     str
packaging_tags                     str
stores                             str
purchase_places                    str
nutriscore_grade                   str
nova_group                     float64
ecoscore_grade                     str
ingredients_text                   str
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
dtype: object

In [8]:
df.columns

Index(['code', 'product_name', 'brands', 'categories_tags', 'countries_tags',
       'packaging_tags', 'stores', 'purchase_places', 'nutriscore_grade',
       'nova_group', 'ecoscore_grade', 'ingredients_text',
       'nutriments.sugars_100g', 'nutriments.energy-kcal_100g'],
      dtype='str')

In [9]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4984    False
4985    False
4986    False
4987    False
4988    False
Length: 4989, dtype: bool

In [10]:
df.code.unique()

array([22222084941, 42111558865, 49000004632, ..., 5942321005454,
       49000056166, 7801610350652], shape=(4989,), dtype=object)

In [11]:
df.code = df.code .replace(',','',regex=True)

In [12]:
df.dtypes

code                            object
product_name                       str
brands                             str
categories_tags                    str
countries_tags                     str
packaging_tags                     str
stores                             str
purchase_places                    str
nutriscore_grade                   str
nova_group                     float64
ecoscore_grade                     str
ingredients_text                   str
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
dtype: object

In [13]:
df.code = df.code.replace('shape=(4989,)','',regex=True)

In [14]:
df.dtypes

code                            object
product_name                       str
brands                             str
categories_tags                    str
countries_tags                     str
packaging_tags                     str
stores                             str
purchase_places                    str
nutriscore_grade                   str
nova_group                     float64
ecoscore_grade                     str
ingredients_text                   str
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
dtype: object

In [15]:
df = df.astype({'code': 'float64'})

In [16]:
df.dtypes

code                           float64
product_name                       str
brands                             str
categories_tags                    str
countries_tags                     str
packaging_tags                     str
stores                             str
purchase_places                    str
nutriscore_grade                   str
nova_group                     float64
ecoscore_grade                     str
ingredients_text                   str
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
dtype: object

In [17]:
df['nutriments.sugars_100g'].unique()

array([           nan, 1.10000000e+01, 1.08291032e+01, 6.76000000e+00,
       1.00000000e+01, 9.80000000e+00, 1.16000000e+01, 8.00000000e+00,
       0.00000000e+00, 1.06000000e+01, 7.91000000e+00, 3.59000000e+00,
       5.50000000e+01, 1.00000000e+00, 1.13000000e+01, 6.50000000e+00,
       9.00000000e+00, 1.07000000e+01, 3.80000000e+01, 7.50000000e+00,
       6.00000000e+00, 3.00000000e+00, 9.39000000e+00, 9.50000000e+00,
       1.20000000e+01, 6.30000000e+00, 1.02000000e+01, 7.90000000e+00,
       2.16000000e+00, 7.30000000e+00, 6.40000000e+01, 5.80000000e+00,
       5.10000000e+00, 1.18000000e+01, 4.20000000e+00, 5.83000000e+00,
       1.30000000e+01, 1.08000000e+01, 7.00000000e+00, 6.67000000e+00,
       5.14000000e+00, 7.70000000e+00, 1.13559322e+01, 8.60000000e+00,
       1.05000000e+01, 4.29000000e+00, 4.40000000e+00, 6.70000000e+00,
       1.35000000e+01, 5.00000000e-01, 5.00000000e+00, 7.80000000e+00,
       4.60000000e+00, 1.04000000e+01, 1.12000000e+01, 9.40000000e+00,
       2.64000000e+01, 7.20000000e+00, 4.55000000e+00, 2.20000000e+01,
       1.80000000e+01, 3.00000000e-01, 4.00000000e-01, 1.08333333e+01,
       7.08000000e+00, 1.18600000e+01, 1.06000004e+01, 2.40000000e+01,
       4.50000000e+00, 8.88888889e+00, 1.46000000e+01, 6.50000000e+01,
       1.03000000e+01, 1.07602752e+01, 9.90000000e+00, 5.93000000e+00,
       2.57143000e+01, 1.32000000e+01, 8.00000000e-01, 1.15000000e+01,
       8.50000000e+00, 6.10000000e+00, 1.09000000e+01, 1.09983080e+01,
       3.50000000e+01, 1.14705882e+01, 4.09999990e+00, 5.40000000e+00,
       5.07042254e+00, 3.20000000e+01, 9.30000000e+00, 4.70000000e+00,
       1.09859155e+01, 1.06493506e+01, 2.00000000e-01, 1.11000000e+01,
       8.40000000e+01, 1.25000000e+00, 1.14798581e+01, 2.60000000e+01,
       3.30000000e+00, 3.00000000e+01, 1.90000000e+01, 8.90000000e+00,
       9.13706000e+00, 1.00000000e-01, 2.50000000e+01, 1.16404169e+01,
       6.92000000e+00, 2.30555556e+01, 1.17117117e+01, 1.09704641e+01,
       1.76000000e+01, 1.08108108e+01, 1.56000000e+01, 5.30000000e+01,
       1.05121294e+01, 1.14640470e+01, 6.97000000e+00, 4.00000000e+01,
       1.00000000e+02, 1.18443316e+01, 1.38418079e+01, 1.21000000e+01,
       4.57000000e+00, 3.10000000e+00, 1.18309859e+01, 1.06000004e+01,
       1.09895498e+01, 1.18309859e+01, 8.10000000e+00, 1.09896303e+01,
       2.80575540e+01, 1.02857143e+01, 1.09800000e+01, 1.04225352e+01,
       3.90000000e+01, 1.39000000e+01, 1.22000000e+01, 4.75000000e+00,
       1.12500000e+01, 7.33000000e+00, 2.00000000e+01, 3.90000000e+00,
       1.90000000e+00, 1.01000000e+01, 1.08300000e+01, 9.01000000e+00,
       2.70000000e+01, 1.30555556e+01, 7.53000000e+00, 1.05714286e+01,
       7.22000000e+00, 1.06000004e+01, 1.33000000e+01, 1.12612613e+01,
       4.80000000e+00, 1.27400000e+01, 4.68000000e+00, 5.85000000e+00,
       1.14638448e+01, 2.40000000e+00, 1.24000000e+01, 8.35000000e+00,
       1.11000004e+01, 4.90000000e+00, 1.14000000e+01, 3.70000000e+00,
       6.70000000e+01, 7.52000000e+00, 1.09859155e+01, 1.10236220e+01,
       8.19999981e+00, 1.07042254e+01, 4.31000000e+01, 6.60000000e+00,
       3.48000000e+01, 4.14000000e+01, 4.71000000e+00, 1.50000000e+01,
       1.85000000e+00, 1.11111111e+01, 3.61000000e+01, 9.09000000e+00,
       2.25000000e+00, 1.27000000e+00, 5.64000000e-01, 1.69000000e+00,
       1.45000000e+00, 8.45000000e-01, 1.13000000e+00, 9.51000000e-01,
       3.05000000e+00, 3.88000000e+00, 2.20000000e+00, 1.52000000e+00,
       1.16000000e+00, 3.30000000e+01, 5.49000000e+00, 3.38000000e+00,
       8.30000000e+01, 5.00000000e+01, 4.20000000e+01, 2.54000000e+00,
       7.25000000e-01, 6.20000000e+00, 3.03000000e+00, 1.84000000e+00,
       3.07000000e-01, 1.48000000e+00, 9.02000000e-01, 9.22000000e-01,
       5.20000000e+01, 9.80000000e+01, 7.70000000e+01, 5.70000000e+01,
       3.14000000e+00, 2.36000000e+00, 2.00000000e+00, 7.20000000e+01,
       4.80000000e+01, 2.90000000e+01, 5.60000000e+01, 1.09000000e+02,
       8.70000000e+01, 5.40000000e+01, 6.92000000e-01, 2.03000000e+00,
       4.06000000e+00, 1.01000000e+00, 1.35000000e+00, 1.93000000e+00,
       9.66000000e-01, 3.33000000e+00, 6.75000000e+00, 9.14000000e+00,
       3.56000000e+00, 8.20000000e+00, 3.60000000e+01, 1.17000000e+01,
       5.17000000e+00, 7.59000000e+00])

In [18]:
df['nutriments.energy-kcal_100g'].unique()

array([           nan, 3.94000000e+01, 3.89170897e+01, 2.71000000e+01,
       4.80000000e+01, 4.20000000e+01, 5.10000000e+01, 3.00000000e+00,
       5.00000000e+01, 4.23000000e+01, 2.00000000e+00, 3.71000000e+01,
       1.50000000e+01, 0.00000000e+00, 4.50000000e+01, 2.20000000e+02,
       1.00000000e+00, 2.00000000e-01, 4.74000000e+01, 9.00000000e-01,
       2.70000000e+01, 4.30000000e+01, 3.00000000e-01, 3.80000000e+01,
       1.50000000e+02, 3.00000000e+01, 2.40000000e+01, 1.20000000e+01,
       4.25000000e+01, 4.08000000e+01, 4.00000000e+01, 4.40000000e+01,
       5.60000000e+01, 2.67000000e-01, 2.86000000e+01, 3.40000000e+01,
       2.50000000e+01, 4.05000000e+01, 4.00000000e-01, 1.68000000e+01,
       2.80000000e+01, 2.00000000e+01, 2.22000000e+01, 5.40000000e+01,
       4.90000000e+01, 4.54000000e-01, 1.90000000e+01, 3.10000000e+01,
       5.00000000e-01, 2.33333333e-01, 4.11864407e+01, 1.05000000e+02,
       3.60000000e+01, 1.71000000e+01, 2.30000000e-01, 4.24000000e+01,
       5.30000000e+01, 2.90000000e+01, 4.78000000e-01, 3.89000000e+01,
       3.90000000e+01, 3.25000000e+02, 8.40000000e+01, 7.00000000e+01,
       3.88888889e+01, 3.33000000e+01, 4.22000000e+01, 1.20000000e+00,
       9.00000000e+01, 2.98500000e-01, 2.80000000e-01, 4.32000000e+01,
       2.92000000e-02, 3.06000000e+00, 3.33333333e+01, 5.35000000e+01,
       4.60000000e+01, 2.40000000e+02, 3.30000000e+01, 4.05715294e+01,
       4.10000000e+01, 4.42000000e+01, 2.15105162e-01, 5.28000000e+01,
       1.00000000e+02, 4.00000000e+00, 4.77000000e+01, 2.30000000e+00,
       4.54100000e-01, 3.00000012e-01, 6.94444444e-01, 3.32217980e+01,
       4.43000000e+01, 2.40000000e-01, 4.06091371e+01, 3.20000000e+01,
       5.94000000e+02, 1.80000000e+02, 4.11764706e+01, 1.80000000e+01,
       2.34225621e+01, 1.97183099e+01, 1.29000000e+02, 1.40000000e+02,
       3.50000000e-01, 1.40000000e+00, 1.30000000e+00, 3.94366197e+01,
       4.30210338e+01, 1.02000000e+00, 6.00000000e+01, 2.45000000e+01,
       6.42000000e+00, 4.17449384e+01, 1.94000000e+01, 4.70000000e+01,
       8.80000000e+01, 3.72000000e+01, 3.38409500e+01, 5.20000000e+01,
       1.80000000e+00, 2.92000000e+01, 4.23287889e+01, 4.31000000e+01,
       5.00000000e+00, 4.00000006e-01, 2.87000000e+01, 8.33333333e+01,
       4.33000000e+01, 4.50450450e+01, 7.50000000e+01, 4.21940928e+01,
       8.00000000e+01, 3.24000000e+01, 4.05405405e+01, 2.00000000e+02,
       2.81690141e-01, 7.00000000e-01, 6.00000000e+00, 2.85000000e+01,
       4.04312668e+01, 4.11529892e+01, 7.09000000e+01, 3.03000000e-01,
       5.45000000e+01, 3.75000000e+02, 4.73773266e+01, 5.64971751e+01,
       1.34000000e+02, 1.65000000e+01, 4.78000000e+01, 1.26000000e+01,
       4.22535211e+01, 3.94496659e+01, 4.22535211e+01, 3.94499549e+01,
       9.20000000e-02, 2.39005743e-01, 1.00719424e+02, 4.40900000e+01,
       1.33333333e+01, 3.69230769e+02, 4.50450450e-01, 3.00000012e-01,
       1.60000000e+01, 1.30000000e+01, 7.20000000e+01, 3.66000000e+01,
       1.10000000e+02, 3.26000000e+01, 6.80000000e-01, 4.25714286e+01,
       2.40000000e+00, 1.91204584e-01, 6.91000000e+00, 4.19000000e+01,
       5.50000000e+01, 1.98000000e+01, 4.71698113e-01, 5.04000000e+01,
       8.00000012e-01, 3.31000000e+01, 2.95000000e+01, 3.70000000e+01,
       1.42000000e+02, 5.59100000e+01, 1.81000000e+01, 4.40917108e+01,
       4.06000000e+01, 1.86000000e+01, 1.85000000e+01, 3.45000000e+01,
       2.00000003e-01, 3.65000000e+01, 2.20000000e+00, 1.18000000e+00,
       1.10659656e+02, 3.85000000e+01, 1.08000000e+02, 2.73000000e-01,
       4.21000000e+01, 2.50000000e+02, 1.88000000e+00, 2.83000000e-01,
       1.45793499e+01, 1.20000000e-01, 6.36000000e+01, 4.17000000e+01,
       3.94366197e+01, 3.25000000e+01, 6.88000000e-01, 6.77000000e-01,
       8.99999976e-01, 4.06000000e-01, 4.49999988e-01, 3.93700787e+01,
       4.54545455e-01, 1.39000000e+02, 7.17017208e-01, 5.00000000e+02,
       4.80000000e-01, 4.88000000e+02, 4.83000000e+02, 4.78000000e+02,
       4.44000000e+01, 4.02000000e-01, 3.89000000e+02, 1.66666667e+01,
       2.87000000e-01, 1.72000000e+01, 4.75000000e+02, 2.60000000e+01,
       1.64000000e+02, 5.20000000e-01, 9.09090909e-01, 9.02000000e+00,
       5.07000000e+00, 2.25000000e+00, 6.76000000e+00, 5.80000000e+00,
       3.38000000e+00, 7.61000000e+00, 4.51000000e+00, 3.80000000e+00,
       1.22000000e+01, 1.55000000e+01, 8.79000000e+00, 6.06000000e+00,
       4.63000000e+00, 1.32000000e+02, 1.24000000e+01, 2.20000000e+01,
       1.35000000e+01, 3.32000000e+02, 1.68000000e+02, 2.68000000e+02,
       6.09000000e+00, 1.01000000e+01, 2.90000000e+00, 2.48000000e+01,
       7.58000000e+00, 1.21000000e+01, 7.38000000e+00, 1.23000000e+00,
       1.60000000e+02, 5.92000000e+00, 3.61000000e+00, 3.69000000e+00,
       2.08000000e+02, 3.92000000e+02, 2.60000000e+02, 3.08000000e+02,
       2.28000000e+02, 2.04000000e+02, 9.44000000e+00, 7.99000000e+00,
       2.32000000e+01, 2.88000000e+02, 1.92000000e+02, 1.16000000e+02,
       7.60000000e+01, 2.24000000e+02, 4.36000000e+02, 3.48000000e+02,
       2.16000000e+02, 2.77000000e+00, 8.12000000e+00, 1.62000000e+01,
       4.06000000e+00, 5.41000000e+00, 7.73000000e+00, 3.86000000e+00,
       2.82000000e-01, 4.00000000e+02, 3.99000000e+01, 4.11000000e+01,
       3.98000000e+01, 2.49000000e+01, 6.67000000e+00, 3.76000000e+01,
       1.33000000e+01, 3.64000000e+00, 1.41000000e+01, 6.21000000e+01,
       2.68000000e+00, 5.68400000e+01, 3.50000000e+01, 8.00000000e-02,
       2.07000000e+01, 3.20000000e+02])

In [19]:
df.isnull().sum()

code                              0
product_name                    260
brands                          389
categories_tags                1954
countries_tags                   28
packaging_tags                 3721
stores                         4429
purchase_places                4449
nutriscore_grade                  1
nova_group                     3084
ecoscore_grade                 4249
ingredients_text               2741
nutriments.sugars_100g         3990
nutriments.energy-kcal_100g    3940
dtype: int64

In [20]:
df.product_name.unique()

<ArrowStringArray>
[               'Coca-Cola original',                    'coca cola zéro',
                         'Coca-Cola',               'Original Taste Soda',
                                 nan,     'Coca-Cola Original Taste Soda',
                         'Pibb Xtra',              'Coca-Cola Zero Sugar',
         'Coca-Cola Zero Sugar Cola',       'Cherry Coca-Cola Zero Sugar',
 ...
                   'Cherry Floaters', 'Coca-Cola Zero Sugar cherry float',
                      'Orange Fanta',                  'Mezzo Mix Cherry',
            'Coca Cola (Zero Sugar)',   'Coca-Cola Zero Sugar Hương Vani',
    'Coca Cola - White Peach Flavor',         'coca cola original tastew',
                    'Coke zero zero',             'Coca-Cola Zero Azucar']
Length: 2902, dtype: str

In [21]:
df.product_name = df.product_name.replace('-','',regex=True)

In [22]:
df.product_name.unique()

<ArrowStringArray>
[               'CocaCola original',                   'coca cola zéro',
                         'CocaCola',              'Original Taste Soda',
                                nan,     'CocaCola Original Taste Soda',
                        'Pibb Xtra',              'CocaCola Zero Sugar',
         'CocaCola Zero Sugar Cola',       'Cherry CocaCola Zero Sugar',
 ...
                  'Cherry Floaters', 'CocaCola Zero Sugar cherry float',
                     'Orange Fanta',                 'Mezzo Mix Cherry',
           'Coca Cola (Zero Sugar)',   'CocaCola Zero Sugar Hương Vani',
    'Coca Cola  White Peach Flavor',        'coca cola original tastew',
                   'Coke zero zero',             'CocaCola Zero Azucar']
Length: 2886, dtype: str

In [23]:
df.product_name = df.product_name.fillna('unknown')

In [24]:
df.product_name.unique()

<ArrowStringArray>
[               'CocaCola original',                   'coca cola zéro',
                         'CocaCola',              'Original Taste Soda',
                          'unknown',     'CocaCola Original Taste Soda',
                        'Pibb Xtra',              'CocaCola Zero Sugar',
         'CocaCola Zero Sugar Cola',       'Cherry CocaCola Zero Sugar',
 ...
                  'Cherry Floaters', 'CocaCola Zero Sugar cherry float',
                     'Orange Fanta',                 'Mezzo Mix Cherry',
           'Coca Cola (Zero Sugar)',   'CocaCola Zero Sugar Hương Vani',
    'Coca Cola  White Peach Flavor',        'coca cola original tastew',
                   'Coke zero zero',             'CocaCola Zero Azucar']
Length: 2886, dtype: str

In [25]:
a=df.product_name[df.product_name== 'unknown'].count()
a

np.int64(260)

In [26]:
df.product_name.isnull().sum()

np.int64(0)

In [27]:
df.brands.isnull().sum()

np.int64(389)

In [28]:
df.brands = df.brands.fillna('unknown')

In [29]:
df.brands.isnull().sum()

np.int64(0)

In [30]:
df.categories_tags = df.categories_tags.fillna('unknown')

In [31]:
df.categories_tags.isnull().sum()

np.int64(0)

In [32]:
df.countries_tags = df.countries_tags.fillna('unknown')

In [33]:
df.countries_tags.isnull().sum()

np.int64(0)

In [34]:
df.packaging_tags = df.packaging_tags.fillna('unknown')

In [35]:
df.packaging_tags.isnull().sum()

np.int64(0)

In [36]:
df.stores = df.stores.fillna('unknown')

In [37]:
df.packaging_tags.isnull().sum()

np.int64(0)

In [38]:
df.purchase_places = df.purchase_places.fillna('unknown')
df.purchase_places.isnull().sum()

np.int64(0)

In [39]:
df.nutriscore_grade = df.nutriscore_grade.fillna('unknown')
df.nutriscore_grade.isnull().sum()

np.int64(0)

In [40]:
df.ecoscore_grade = df.ecoscore_grade.fillna('unknown')
df.ecoscore_grade.isnull().sum()

np.int64(0)

In [41]:
df.ingredients_text = df.ingredients_text.fillna('unknown')
df.ingredients_text.isnull().sum()

np.int64(0)

In [42]:
df.isnull().sum()

code                              0
product_name                      0
brands                            0
categories_tags                   0
countries_tags                    0
packaging_tags                    0
stores                            0
purchase_places                   0
nutriscore_grade                  0
nova_group                     3084
ecoscore_grade                    0
ingredients_text                  0
nutriments.sugars_100g         3990
nutriments.energy-kcal_100g    3940
dtype: int64

In [43]:
df.code = df.code.replace('coca cola','Coca-Cola',regex=True)

In [44]:
df.code = df.code.replace('Coca-cola','Coca-Cola',regex=True)

In [45]:
df.code = df.code.replace('Cocacola','Coca-Cola',regex=True)

In [46]:
raw_products = df.product_name.str.split(',')
raw_products

0            [CocaCola original]
1               [coca cola zéro]
2                     [CocaCola]
3                     [CocaCola]
4          [Original Taste Soda]
                  ...
4984                   [unknown]
4985       [Coca Cola Coca Cola]
4986            [Coke zero zero]
4987    [Cherry Float Coke Zero]
4988      [CocaCola Zero Azucar]
Name: product_name, Length: 4989, dtype: object

In [47]:
exploded_products = raw_products.explode()
exploded_products

0            CocaCola original
1               coca cola zéro
2                     CocaCola
3                     CocaCola
4          Original Taste Soda
                 ...
4984                   unknown
4985       Coca Cola Coca Cola
4986            Coke zero zero
4987    Cherry Float Coke Zero
4988      CocaCola Zero Azucar
Name: product_name, Length: 5517, dtype: str

In [48]:
exploded_products.value_counts()

product_name
unknown                           260
CocaCola                          183
Coca cola                         175
Coca Cola                         128
 Coca Cola                         86
                                 ...
CocaCola Zero Sugar Hương Vani      1
Coca Cola  White Peach Flavor       1
coca cola original tastew           1
Coke zero zero                      1
CocaCola Zero Azucar                1
Name: count, Length: 2914, dtype: int64

In [49]:
raw_products = df.product_name.str.lower()
raw_products

0            cocacola original
1               coca cola zéro
2                     cocacola
3                     cocacola
4          original taste soda
                 ...
4984                   unknown
4985       coca cola coca cola
4986            coke zero zero
4987    cherry float coke zero
4988      cocacola zero azucar
Name: product_name, Length: 4989, dtype: str

In [50]:
raw_products.unique()

<ArrowStringArray>
[               'cocacola original',                   'coca cola zéro',
                         'cocacola',              'original taste soda',
                          'unknown',     'cocacola original taste soda',
                        'pibb xtra',              'cocacola zero sugar',
         'cocacola zero sugar cola',       'cherry cocacola zero sugar',
 ...
                             'アンバサ',           'sprite mint zero sugar',
                  'cherry floaters', 'cocacola zero sugar cherry float',
                     'orange fanta',                 'mezzo mix cherry',
           'coca cola (zero sugar)',   'cocacola zero sugar hương vani',
    'coca cola  white peach flavor',        'coca cola original tastew']
Length: 2585, dtype: str

In [51]:
df.isnull().sum()

code                              0
product_name                      0
brands                            0
categories_tags                   0
countries_tags                    0
packaging_tags                    0
stores                            0
purchase_places                   0
nutriscore_grade                  0
nova_group                     3084
ecoscore_grade                    0
ingredients_text                  0
nutriments.sugars_100g         3990
nutriments.energy-kcal_100g    3940
dtype: int64

In [52]:
df.dtypes

code                           float64
product_name                       str
brands                             str
categories_tags                    str
countries_tags                     str
packaging_tags                     str
stores                             str
purchase_places                    str
nutriscore_grade                   str
nova_group                     float64
ecoscore_grade                     str
ingredients_text                   str
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
dtype: object

In [53]:
df['product_name'] = df['product_name'].str.lower().str.split(',')

df['product_name'] = [
    [item.strip() for item in row]
    for row in df['product_name']
]

In [54]:
df.categories_tags

0              beverages, carbonated-drinks, sodas, colas
1       beverages, carbonated-drinks, artificially-swe...
2       beverages-and-beverages-preparations, beverage...
3                                                 unknown
4       beverages-and-beverages-preparations, beverage...
                              ...
4984    beverages-and-beverages-preparations, beverage...
4985                                          Dagligvarer
4986                                              unknown
4987                                              unknown
4988    beverages-and-beverages-preparations, beverage...
Name: categories_tags, Length: 4989, dtype: str

In [55]:
df.packaging_tags

0                      unknown
1              plastic, bottle
2       bottle-or-vial, bottle
3                      unknown
4                      unknown
                 ...
4984                   unknown
4985                   unknown
4986                   unknown
4987                   unknown
4988                   unknown
Name: packaging_tags, Length: 4989, dtype: str

In [56]:
df['packaging_tags'] = df['packaging_tags'].str.lower().str.split(',')

df['packaging_tags'] = [
    [item.strip() for item in row]
    for row in df['packaging_tags']
]

In [57]:
df.packaging_tags

0                      [unknown]
1              [plastic, bottle]
2       [bottle-or-vial, bottle]
3                      [unknown]
4                      [unknown]
                  ...
4984                   [unknown]
4985                   [unknown]
4986                   [unknown]
4987                   [unknown]
4988                   [unknown]
Name: packaging_tags, Length: 4989, dtype: object

In [58]:
packaging_tags = df.packaging_tags.explode()

In [59]:
df.packaging_tags

0                      [unknown]
1              [plastic, bottle]
2       [bottle-or-vial, bottle]
3                      [unknown]
4                      [unknown]
                  ...
4984                   [unknown]
4985                   [unknown]
4986                   [unknown]
4987                   [unknown]
4988                   [unknown]
Name: packaging_tags, Length: 4989, dtype: object

In [60]:
df['stores'] = df['stores'].str.lower().str.split(',')

df['stores'] = [
    [item.strip() for item in row]
    for row in df['stores']
]

In [61]:
df['purchase_places'] = df['purchase_places'].str.lower().str.split(',')

df['purchase_places'] = [
    [item.strip() for item in row]
    for row in df['purchase_places']
]

In [62]:
df['nutriscore_grade'] = df['nutriscore_grade'].str.lower().str.split(',')

df['nutriscore_grades'] = [
    [item.strip() for item in row]
    for row in df['nutriscore_grade']
]

In [63]:
df['ecoscore_grades'] = df['ecoscore_grade'].str.lower().str.split(',')

df['ecoscore_grades'] = [
    [item.strip() for item in row]
    for row in df['ecoscore_grade']
]

In [64]:
df['ingredients_text'] = df['ingredients_text'].str.lower().str.split(',')

df['ingredients_text'] = [
    [item.strip() for item in row]
    for row in df['ingredients_text']
]

In [65]:
df.head()

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g,nutriscore_grades,ecoscore_grades
0,2.222208e+10,[cocacola original],Coca-Cola,"beverages, carbonated-drinks, sodas, colas",spain,[unknown],[unknown],[unknown],[unknown],NaN,unknown,[unknown],NaN,NaN,[unknown],"[u, n, k, n, o, w, n]"
1,4.211156e+10,[coca cola zéro],"Coca-Cola-light, coca cola","beverages, carbonated-drinks, artificially-swe...",france,"[plastic, bottle]",[unknown],[unknown],[unknown],NaN,unknown,[unknown],NaN,NaN,[unknown],"[u, n, k, n, o, w, n]"
2,4.900000e+10,[cocacola],Coca-Cola,"beverages-and-beverages-preparations, beverage...","france, united-states","[bottle-or-vial, bottle]",[unknown],[unknown],[e],4.0,unknown,"[carbonated water, cane sugar, caramel color, ...",NaN,NaN,[e],"[u, n, k, n, o, w, n]"
3,4.900001e+10,[cocacola],Coca-Cola,unknown,united-states,[unknown],[unknown],[unknown],[unknown],4.0,unknown,"[carbonated water, high fructose corn syrup, c...",11.0,39.4,[unknown],"[u, n, k, n, o, w, n]"
4,4.900002e+10,[original taste soda],Coca-Cola,"beverages-and-beverages-preparations, beverage...","france, united-states",[unknown],[unknown],[unknown],[e],4.0,unknown,[caffeiedo amount/serving % daily value nutrit...,NaN,NaN,[e],"[u, n, k, n, o, w, n]"

In [66]:
df['product_name'].map(tuple).unique()

array([('cocacola original',), ('coca cola zéro',), ('cocacola',), ...,
       ('cocacola zero sugar hương vani',),
       ('coca cola  white peach flavor',), ('coca cola original tastew',)],
      shape=(2581,), dtype=object)

In [67]:
df['product_name'].head(10)

0               [cocacola original]
1                  [coca cola zéro]
2                        [cocacola]
3                        [cocacola]
4             [original taste soda]
5                         [unknown]
6    [cocacola original taste soda]
7                       [pibb xtra]
8             [cocacola zero sugar]
9             [cocacola zero sugar]
Name: product_name, dtype: object

In [68]:
df.head()

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g,nutriscore_grades,ecoscore_grades
0,2.222208e+10,[cocacola original],Coca-Cola,"beverages, carbonated-drinks, sodas, colas",spain,[unknown],[unknown],[unknown],[unknown],NaN,unknown,[unknown],NaN,NaN,[unknown],"[u, n, k, n, o, w, n]"
1,4.211156e+10,[coca cola zéro],"Coca-Cola-light, coca cola","beverages, carbonated-drinks, artificially-swe...",france,"[plastic, bottle]",[unknown],[unknown],[unknown],NaN,unknown,[unknown],NaN,NaN,[unknown],"[u, n, k, n, o, w, n]"
2,4.900000e+10,[cocacola],Coca-Cola,"beverages-and-beverages-preparations, beverage...","france, united-states","[bottle-or-vial, bottle]",[unknown],[unknown],[e],4.0,unknown,"[carbonated water, cane sugar, caramel color, ...",NaN,NaN,[e],"[u, n, k, n, o, w, n]"
3,4.900001e+10,[cocacola],Coca-Cola,unknown,united-states,[unknown],[unknown],[unknown],[unknown],4.0,unknown,"[carbonated water, high fructose corn syrup, c...",11.0,39.4,[unknown],"[u, n, k, n, o, w, n]"
4,4.900002e+10,[original taste soda],Coca-Cola,"beverages-and-beverages-preparations, beverage...","france, united-states",[unknown],[unknown],[unknown],[e],4.0,unknown,[caffeiedo amount/serving % daily value nutrit...,NaN,NaN,[e],"[u, n, k, n, o, w, n]"

In [69]:
df.isnull().sum()

code                              0
product_name                      0
brands                            0
categories_tags                   0
countries_tags                    0
packaging_tags                    0
stores                            0
purchase_places                   0
nutriscore_grade                  0
nova_group                     3084
ecoscore_grade                    0
ingredients_text                  0
nutriments.sugars_100g         3990
nutriments.energy-kcal_100g    3940
nutriscore_grades                 0
ecoscore_grades                   0
dtype: int64

In [70]:
df.dtypes

code                           float64
product_name                    object
brands                             str
categories_tags                    str
countries_tags                     str
packaging_tags                  object
stores                          object
purchase_places                 object
nutriscore_grade                object
nova_group                     float64
ecoscore_grade                     str
ingredients_text                object
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
nutriscore_grades               object
ecoscore_grades                 object
dtype: object

In [71]:
df['brands'] = df['brands'].str.lower().str.split(',')

df['brands'] = [
    [item.strip() for item in row]
    for row in df['brands']
]

In [72]:
df['ecoscore_grade'] = df['ecoscore_grade'].str.lower().str.split(',')

df['ecoscore_grade'] = [
    [item.strip() for item in row]
    for row in df['ecoscore_grade']
]

In [73]:
df.dtypes

code                           float64
product_name                    object
brands                          object
categories_tags                    str
countries_tags                     str
packaging_tags                  object
stores                          object
purchase_places                 object
nutriscore_grade                object
nova_group                     float64
ecoscore_grade                  object
ingredients_text                object
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
nutriscore_grades               object
ecoscore_grades                 object
dtype: object

In [74]:
cat_cols = df.select_dtypes(include='object').columns

df[cat_cols] = df[cat_cols].astype('string')

/var/folders/bz/hvzhy0zx4mdcy6mrw7g2bcmh0000gn/T/ipykernel_16039/1094818609.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns

In [75]:
df.dtypes

code                           float64
product_name                    string
brands                          string
categories_tags                 string
countries_tags                  string
packaging_tags                  string
stores                          string
purchase_places                 string
nutriscore_grade                string
nova_group                     float64
ecoscore_grade                  string
ingredients_text                string
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
nutriscore_grades               string
ecoscore_grades                 string
dtype: object

In [76]:
df['product_name'].unique()

<ArrowStringArray>
[               '['cocacola original']',
                   '['coca cola zéro']',
                         '['cocacola']',
              '['original taste soda']',
                          '['unknown']',
     '['cocacola original taste soda']',
                        '['pibb xtra']',
              '['cocacola zero sugar']',
         '['cocacola zero sugar cola']',
       '['cherry cocacola zero sugar']',
 ...
                             '['アンバサ']',
           '['sprite mint zero sugar']',
                  '['cherry floaters']',
 '['cocacola zero sugar cherry float']',
                     '['orange fanta']',
                 '['mezzo mix cherry']',
           '['coca cola (zero sugar)']',
   '['cocacola zero sugar hương vani']',
    '['coca cola  white peach flavor']',
        '['coca cola original tastew']']
Length: 2581, dtype: string

In [77]:
df['brands'].unique()

<ArrowStringArray>
[                                                        '['coca-cola']',
                                      '['coca-cola-light', 'coca cola']',
                                                 '['coca-cola company']',
                             '['coca-cola', 'coca-cola original taste']',
                                                 '['coca-cola', 'coke']',
                                                              '['coke']',
                                      '['coca-cola', 'coca-cola-light']',
                               '["mcdonald's", 'the coca-cola company']',
                                          '['minute maid', 'coca cola']',
                                          '['minute maid', 'coca-cola']',
 ...
                                      '['quoted coca &quot;cola&quot;']',
                                                '['slice', 'coca-cola']',
                                       '['georgia coffee', 'coca-cola']',
                                     '['coca-cola company', 'cocacola']',
                                                              '['jack']',
                                        '['coca-cola company', 'maaza']',
                                                          '['original']',
                                   '['minute maid', 'coca-cola', 'mzy']',
 '['coca-cola company', 'coca-cola drikker as', 'urge', 'urge intense']',
                    '['nordic', 'nordic mist', 'the coca-cola company']']
Length: 508, dtype: string

In [78]:
df = df.explode('brands')

In [79]:
df['brands'].unique()

<ArrowStringArray>
[                                                        '['coca-cola']',
                                      '['coca-cola-light', 'coca cola']',
                                                 '['coca-cola company']',
                             '['coca-cola', 'coca-cola original taste']',
                                                 '['coca-cola', 'coke']',
                                                              '['coke']',
                                      '['coca-cola', 'coca-cola-light']',
                               '["mcdonald's", 'the coca-cola company']',
                                          '['minute maid', 'coca cola']',
                                          '['minute maid', 'coca-cola']',
 ...
                                      '['quoted coca &quot;cola&quot;']',
                                                '['slice', 'coca-cola']',
                                       '['georgia coffee', 'coca-cola']',
                                     '['coca-cola company', 'cocacola']',
                                                              '['jack']',
                                        '['coca-cola company', 'maaza']',
                                                          '['original']',
                                   '['minute maid', 'coca-cola', 'mzy']',
 '['coca-cola company', 'coca-cola drikker as', 'urge', 'urge intense']',
                    '['nordic', 'nordic mist', 'the coca-cola company']']
Length: 508, dtype: string

In [80]:
df = df.explode('product_name')

In [81]:
df['categories_tags'].unique()

<ArrowStringArray>
[                                                                                                                                                                                                                               'beverages, carbonated-drinks, sodas, colas',
                                                                                                                                            'beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink',
                                                                                                                                                                     'beverages-and-beverages-preparations, beverages, carbonated-drinks, sodas, colas, sweetened-beverages',
                                                                                                                                                                                                                                                                   'unknown',
                                                                                                                               'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, carbonated-drinks, soft-drinks, sodas, colas, sweetened-beverages',
                                                                                                                                                                                                                   'beverages-and-beverages-preparations, beverages, waters',
                                                                                                                                                                                                                                       'beverages, carbonated-drinks, sodas',
                                                                                                      'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink',
                                             'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink, Bebidas, Bebidas-gaseosas, Refrescos, Refrescos-de-cola',
                                                                                                                                                                  'beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas',
 ...
                            'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, carbonated-soft-drinks-without-fruit-juice, carbonated-soft-drinks-without-fruit-juice-with-reduced-sugar, Cold d',
                                                                                                                                                     'beverages-and-beverages-preparations, beverages, carbonated-drinks, sodas, carbonated-soft-drinks-without-fruit-juice',
                                                                                                                                         'beverages-and-beverages-preparations, plant-based-foods-and-beverages, beverages, sweetened-beverages, Ready to serve fruit drink',
                                                                                                                                                                                     'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, soft-drinks',
                                                                                                                                                                                                                                           'Coca-Cola, Coke, Coke zero zero',
 'beverages-and-beverages-preparations, plant-based-foods-and-beverages, beverages, plant-based-foods, fruits-and-vegetables-based-foods, fruits-based-foods, fruits, plant-based-beverages, fruit-based-beverages, juices-and-nectars, fruit-juices, peaches, peach-juices',
                                                                                                                                                                                                                                                              'pt:Coca-cola',
                                                                                                                                                                                                                                                                   'he:סודה',
                                                                                                                                                                                                                                                               'Dagligvarer',
                                                                                                  'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, carbonated-drinks, soft-drinks, sweeteners, sodas, sugars, colas, Coca-Cola, Libre de calorías']
Length: 784, dtype: string

In [82]:
df = df.explode('categories_tags')

In [83]:
df.categories_tags

0              beverages, carbonated-drinks, sodas, colas
1       beverages, carbonated-drinks, artificially-swe...
2       beverages-and-beverages-preparations, beverage...
3                                                 unknown
4       beverages-and-beverages-preparations, beverage...
                              ...
4984    beverages-and-beverages-preparations, beverage...
4985                                          Dagligvarer
4986                                              unknown
4987                                              unknown
4988    beverages-and-beverages-preparations, beverage...
Name: categories_tags, Length: 4989, dtype: string

In [84]:
df = df.explode('categories_tags')

In [85]:
df['product_name'].unique()

<ArrowStringArray>
[               '['cocacola original']',
                   '['coca cola zéro']',
                         '['cocacola']',
              '['original taste soda']',
                          '['unknown']',
     '['cocacola original taste soda']',
                        '['pibb xtra']',
              '['cocacola zero sugar']',
         '['cocacola zero sugar cola']',
       '['cherry cocacola zero sugar']',
 ...
                             '['アンバサ']',
           '['sprite mint zero sugar']',
                  '['cherry floaters']',
 '['cocacola zero sugar cherry float']',
                     '['orange fanta']',
                 '['mezzo mix cherry']',
           '['coca cola (zero sugar)']',
   '['cocacola zero sugar hương vani']',
    '['coca cola  white peach flavor']',
        '['coca cola original tastew']']
Length: 2581, dtype: string

In [86]:
type(df['product_name'].iloc[0])

str

In [87]:
df.product_name.head()

0      ['cocacola original']
1         ['coca cola zéro']
2               ['cocacola']
3               ['cocacola']
4    ['original taste soda']
Name: product_name, dtype: string

In [88]:
df['product_name'].unique()

<ArrowStringArray>
[               '['cocacola original']',
                   '['coca cola zéro']',
                         '['cocacola']',
              '['original taste soda']',
                          '['unknown']',
     '['cocacola original taste soda']',
                        '['pibb xtra']',
              '['cocacola zero sugar']',
         '['cocacola zero sugar cola']',
       '['cherry cocacola zero sugar']',
 ...
                             '['アンバサ']',
           '['sprite mint zero sugar']',
                  '['cherry floaters']',
 '['cocacola zero sugar cherry float']',
                     '['orange fanta']',
                 '['mezzo mix cherry']',
           '['coca cola (zero sugar)']',
   '['cocacola zero sugar hương vani']',
    '['coca cola  white peach flavor']',
        '['coca cola original tastew']']
Length: 2581, dtype: string

In [89]:
df['product_name'] = df['product_name'].str.replace('cocacola', 'coca-cola', regex=False)
df['product_name'] = df['product_name'].str.replace('coca cola', 'coca-cola', regex=False)

In [90]:
df['product_name'] = df['product_name'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [91]:
df['product_name'].unique()

<ArrowStringArray>
[             '['coca-cola original']',                  '['coca-cola zéro']',
                       '['coca-cola']',             '['original taste soda']',
                         '['unknown']',   '['coca-cola original taste soda']',
                       '['pibb xtra']',            '['coca-cola zero sugar']',
       '['coca-cola zero sugar cola']',     '['cherry coca-cola zero sugar']',
 ...
            '['cepita manzana 900ml']',                            '['アンバサ']',
          '['sprite mint zero sugar']',                 '['cherry floaters']',
                    '['orange fanta']',                '['mezzo mix cherry']',
          '['coca-cola (zero sugar)']', '['coca-cola zero sugar hương vani']',
    '['coca-cola white peach flavor']',       '['coca-cola original tastew']']
Length: 2482, dtype: string

In [92]:
df = df.explode('brands')

In [93]:
df['brands'].unique()

<ArrowStringArray>
[                                                        '['coca-cola']',
                                      '['coca-cola-light', 'coca cola']',
                                                 '['coca-cola company']',
                             '['coca-cola', 'coca-cola original taste']',
                                                 '['coca-cola', 'coke']',
                                                              '['coke']',
                                      '['coca-cola', 'coca-cola-light']',
                               '["mcdonald's", 'the coca-cola company']',
                                          '['minute maid', 'coca cola']',
                                          '['minute maid', 'coca-cola']',
 ...
                                      '['quoted coca &quot;cola&quot;']',
                                                '['slice', 'coca-cola']',
                                       '['georgia coffee', 'coca-cola']',
                                     '['coca-cola company', 'cocacola']',
                                                              '['jack']',
                                        '['coca-cola company', 'maaza']',
                                                          '['original']',
                                   '['minute maid', 'coca-cola', 'mzy']',
 '['coca-cola company', 'coca-cola drikker as', 'urge', 'urge intense']',
                    '['nordic', 'nordic mist', 'the coca-cola company']']
Length: 508, dtype: string

In [94]:

df['brands'] = df['brands'].str.replace('coca cola', 'coca-cola', regex=False)
df['brands'] = df['brands'].str.replace('cocacola', 'coca-cola', regex=False)
df['brands'] = df['brands'].str.replace('the coca-cola company', 'coca-cola company', regex=False)

In [95]:
df['brands'].unique()

<ArrowStringArray>
[                                                        '['coca-cola']',
                                      '['coca-cola-light', 'coca-cola']',
                                                 '['coca-cola company']',
                             '['coca-cola', 'coca-cola original taste']',
                                                 '['coca-cola', 'coke']',
                                                              '['coke']',
                                      '['coca-cola', 'coca-cola-light']',
                                   '["mcdonald's", 'coca-cola company']',
                                          '['minute maid', 'coca-cola']',
                          '['brasserie de tahiti', 'coca-cola company']',
 ...
                                        '['販売者/コカ•コーラ カスタマーマーケティング(株)']',
                                      '['quoted coca &quot;cola&quot;']',
                                                '['slice', 'coca-cola']',
                                       '['georgia coffee', 'coca-cola']',
                                                              '['jack']',
                                        '['coca-cola company', 'maaza']',
                                                          '['original']',
                                   '['minute maid', 'coca-cola', 'mzy']',
 '['coca-cola company', 'coca-cola drikker as', 'urge', 'urge intense']',
                        '['nordic', 'nordic mist', 'coca-cola company']']
Length: 444, dtype: string

In [96]:
df[df['brands'].str.contains('original', case=False, na=False)]

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g,nutriscore_grades,ecoscore_grades
14,4.900005e+10,['coca-cola'],"['coca-cola', 'coca-cola original taste']","beverages-and-beverages-preparations, beverage...",united-states,"['plastic', 'bottle-or-vial', 'bottle', 'pet-b...",['unknown'],['unknown'],['e'],4.0,['unknown'],['carbonated water high fructose corn syrup ca...,NaN,NaN,['e'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
3236,7.894900e+12,['pack refrigerante coca-cola original lata 6 ...,['coca-cola original'],unknown,brazil,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4592,1.234066e+12,['coca-cola'],['original taste'],unknown,united-kingdom,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4902,5.000113e+12,['coca-cola'],['original'],unknown,austria,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"

In [97]:
df[df['brands'].str.contains('jack', case=False, na=False)]

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g,nutriscore_grades,ecoscore_grades
3032,8.218401e+10,"[""jack daniel's & coca-cola zero sugar""]","[""jack daniel's & coca-cola""]",pre-mixed-alcoholic-beverage,united-states,['unknown'],['unknown'],['unknown'],['unknown'],4.0,['unknown'],"['caramel color added', 'caffeine free', 'cont...",20.0,25.0,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
3498,5.449000e+12,"[""jack daniel's cola""]","[""jack daniel's"", 'coca-cola']","beverages-and-beverages-preparations, beverages",germany,['unknown'],['unknown'],['unknown'],['unknown'],4.0,['unknown'],"['coca-cola (sprankelend water', ""suiker; kleu...",NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
3873,5.000113e+12,['jd coca-cola'],['jack daniels'],unknown,united-kingdom,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4298,5.099873e+12,['gentleman jack mit coca-cola'],['jack daniels'],"beverages-and-beverages-preparations, beverages",germany,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4576,5.449000e+12,"[""jack daniel's tennessee whiskey mixed with c...",['jack & coke'],unknown,netherlands,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4702,9.300675e+12,"[""jack daniel's tennessee whiskey mixed with c...","[""jack daniel's""]",unknown,united-states,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4738,9.300675e+12,['tennessee whiskey mixed with coca-cola'],"[""jack daniel's""]",unknown,united-states,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4889,5.449000e+12,['jack daniels coca-cola'],['jack'],unknown,netherlands,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4940,5.449000e+12,"[""jack daniel's tennessee whiskey mixed with c...",['jack'],unknown,netherlands,['unknown'],['unknown'],['unknown'],['unknown'],NaN,['unknown'],['unknown'],NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"

In [98]:
df[df['brands'].str.contains('mzy', case=False, na=False)]

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g,nutriscore_grades,ecoscore_grades
4946,6.975682e+12,['mzy peach juice drink'],"['minute maid', 'coca-cola', 'mzy']","beverages-and-beverages-preparations, plant-ba...","china, united-kingdom",['unknown'],['unknown'],['unknown'],['e'],4.0,['unknown'],"['water', 'fructose syrup', 'sugar', 'concentr...",NaN,NaN,['e'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"

In [99]:
df.brands.unique()

<ArrowStringArray>
[                                                        '['coca-cola']',
                                      '['coca-cola-light', 'coca-cola']',
                                                 '['coca-cola company']',
                             '['coca-cola', 'coca-cola original taste']',
                                                 '['coca-cola', 'coke']',
                                                              '['coke']',
                                      '['coca-cola', 'coca-cola-light']',
                                   '["mcdonald's", 'coca-cola company']',
                                          '['minute maid', 'coca-cola']',
                          '['brasserie de tahiti', 'coca-cola company']',
 ...
                                        '['販売者/コカ•コーラ カスタマーマーケティング(株)']',
                                      '['quoted coca &quot;cola&quot;']',
                                                '['slice', 'coca-cola']',
                                       '['georgia coffee', 'coca-cola']',
                                                              '['jack']',
                                        '['coca-cola company', 'maaza']',
                                                          '['original']',
                                   '['minute maid', 'coca-cola', 'mzy']',
 '['coca-cola company', 'coca-cola drikker as', 'urge', 'urge intense']',
                        '['nordic', 'nordic mist', 'coca-cola company']']
Length: 444, dtype: string

In [100]:
import html

df['brands'] = df['brands'].apply(html.unescape)

In [101]:
print(df['brands'].nunique())
print(df['brands'].value_counts().head(20))

444
brands
['coca-cola']                                  3084
['unknown']                                     389
['coca-cola company']                           198
['coca-cola', 'coca-cola-light']                 89
['fanta', 'coca-cola']                           55
['coca-cola european partners norge a']          50
['coca-cola', 'coca-cola company']               44
['coke']                                         43
['coca-cola europacific partners norge as']      32
['coca-cola', 'coke']                            30
['coca-cola zero']                               24
["zaxby's"]                                      24
['coca-cola', 'coca-cola']                       23
['fanta', 'coca-cola company']                   23
['sonic']                                        20
['white castle']                                 16
['coca-cola company', 'coca-cola']               15
['coca']                                         15
['coca-cola', 'fuzetea']                         14
['sprite', 'coca-cola']                          13
Name: count, dtype: int64

In [102]:
df['categories_tags'].unique()

<ArrowStringArray>
[                                                                                                                                                                                                                               'beverages, carbonated-drinks, sodas, colas',
                                                                                                                                            'beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink',
                                                                                                                                                                     'beverages-and-beverages-preparations, beverages, carbonated-drinks, sodas, colas, sweetened-beverages',
                                                                                                                                                                                                                                                                   'unknown',
                                                                                                                               'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, carbonated-drinks, soft-drinks, sodas, colas, sweetened-beverages',
                                                                                                                                                                                                                   'beverages-and-beverages-preparations, beverages, waters',
                                                                                                                                                                                                                                       'beverages, carbonated-drinks, sodas',
                                                                                                      'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink',
                                             'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink, Bebidas, Bebidas-gaseosas, Refrescos, Refrescos-de-cola',
                                                                                                                                                                  'beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas',
 ...
                            'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, carbonated-soft-drinks-without-fruit-juice, carbonated-soft-drinks-without-fruit-juice-with-reduced-sugar, Cold d',
                                                                                                                                                     'beverages-and-beverages-preparations, beverages, carbonated-drinks, sodas, carbonated-soft-drinks-without-fruit-juice',
                                                                                                                                         'beverages-and-beverages-preparations, plant-based-foods-and-beverages, beverages, sweetened-beverages, Ready to serve fruit drink',
                                                                                                                                                                                     'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, soft-drinks',
                                                                                                                                                                                                                                           'Coca-Cola, Coke, Coke zero zero',
 'beverages-and-beverages-preparations, plant-based-foods-and-beverages, beverages, plant-based-foods, fruits-and-vegetables-based-foods, fruits-based-foods, fruits, plant-based-beverages, fruit-based-beverages, juices-and-nectars, fruit-juices, peaches, peach-juices',
                                                                                                                                                                                                                                                              'pt:Coca-cola',
                                                                                                                                                                                                                                                                   'he:סודה',
                                                                                                                                                                                                                                                               'Dagligvarer',
                                                                                                  'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, carbonated-drinks, soft-drinks, sweeteners, sodas, sugars, colas, Coca-Cola, Libre de calorías']
Length: 784, dtype: string

In [103]:
df = df.explode('categories_tags')

In [104]:
df['categories_tags'] = df['categories_tags'].str.strip()

In [105]:
print(df['categories_tags'].unique())

<ArrowStringArray>
[                                                                                                                                                                                                                               'beverages, carbonated-drinks, sodas, colas',
                                                                                                                                            'beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink',
                                                                                                                                                                     'beverages-and-beverages-preparations, beverages, carbonated-drinks, sodas, colas, sweetened-beverages',
                                                                                                                                                                                                                                                                   'unknown',
                                                                                                                               'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, carbonated-drinks, soft-drinks, sodas, colas, sweetened-beverages',
                                                                                                                                                                                                                   'beverages-and-beverages-preparations, beverages, waters',
                                                                                                                                                                                                                                       'beverages, carbonated-drinks, sodas',
                                                                                                      'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink',
                                             'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink, Bebidas, Bebidas-gaseosas, Refrescos, Refrescos-de-cola',
                                                                                                                                                                  'beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas',
 ...
                            'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, carbonated-soft-drinks-without-fruit-juice, carbonated-soft-drinks-without-fruit-juice-with-reduced-sugar, Cold d',
                                                                                                                                                     'beverages-and-beverages-preparations, beverages, carbonated-drinks, sodas, carbonated-soft-drinks-without-fruit-juice',
                                                                                                                                         'beverages-and-beverages-preparations, plant-based-foods-and-beverages, beverages, sweetened-beverages, Ready to serve fruit drink',
                                                                                                                                                                                     'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, soft-drinks',
                                                                                                                                                                                                                                           'Coca-Cola, Coke, Coke zero zero',
 'beverages-and-beverages-preparations, plant-based-foods-and-beverages, beverages, plant-based-foods, fruits-and-vegetables-based-foods, fruits-based-foods, fruits, plant-based-beverages, fruit-based-beverages, juices-and-nectars, fruit-juices, peaches, peach-juices',
                                                                                                                                                                                                                                                              'pt:Coca-cola',
                                                                                                                                                                                                                                                                   'he:סודה',
                                                                                                                                                                                                                                                               'Dagligvarer',
                                                                                                  'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, carbonated-drinks, soft-drinks, sweeteners, sodas, sugars, colas, Coca-Cola, Libre de calorías']
Length: 784, dtype: string

In [106]:
df['categories_tags'].unique()

<ArrowStringArray>
[                                                                                                                                                                                                                               'beverages, carbonated-drinks, sodas, colas',
                                                                                                                                            'beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink',
                                                                                                                                                                     'beverages-and-beverages-preparations, beverages, carbonated-drinks, sodas, colas, sweetened-beverages',
                                                                                                                                                                                                                                                                   'unknown',
                                                                                                                               'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, carbonated-drinks, soft-drinks, sodas, colas, sweetened-beverages',
                                                                                                                                                                                                                   'beverages-and-beverages-preparations, beverages, waters',
                                                                                                                                                                                                                                       'beverages, carbonated-drinks, sodas',
                                                                                                      'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink',
                                             'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas, diet-cola-soft-drink, Bebidas, Bebidas-gaseosas, Refrescos, Refrescos-de-cola',
                                                                                                                                                                  'beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, colas, diet-sodas',
 ...
                            'beverages-and-beverages-preparations, beverages, carbonated-drinks, artificially-sweetened-beverages, sodas, diet-beverages, carbonated-soft-drinks-without-fruit-juice, carbonated-soft-drinks-without-fruit-juice-with-reduced-sugar, Cold d',
                                                                                                                                                     'beverages-and-beverages-preparations, beverages, carbonated-drinks, sodas, carbonated-soft-drinks-without-fruit-juice',
                                                                                                                                         'beverages-and-beverages-preparations, plant-based-foods-and-beverages, beverages, sweetened-beverages, Ready to serve fruit drink',
                                                                                                                                                                                     'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, soft-drinks',
                                                                                                                                                                                                                                           'Coca-Cola, Coke, Coke zero zero',
 'beverages-and-beverages-preparations, plant-based-foods-and-beverages, beverages, plant-based-foods, fruits-and-vegetables-based-foods, fruits-based-foods, fruits, plant-based-beverages, fruit-based-beverages, juices-and-nectars, fruit-juices, peaches, peach-juices',
                                                                                                                                                                                                                                                              'pt:Coca-cola',
                                                                                                                                                                                                                                                                   'he:סודה',
                                                                                                                                                                                                                                                               'Dagligvarer',
                                                                                                  'beverages-and-beverages-preparations, beverages, non-alcoholic-beverages, carbonated-drinks, soft-drinks, sweeteners, sodas, sugars, colas, Coca-Cola, Libre de calorías']
Length: 784, dtype: string

In [107]:
df.dtypes

code                           float64
product_name                    string
brands                             str
categories_tags                 string
countries_tags                  string
packaging_tags                  string
stores                          string
purchase_places                 string
nutriscore_grade                string
nova_group                     float64
ecoscore_grade                  string
ingredients_text                string
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
nutriscore_grades               string
ecoscore_grades                 string
dtype: object

In [108]:
df['countries_tags'].unique()

<ArrowStringArray>
[                                                                                                              'spain',
                                                                                                              'france',
                                                                                               'france, united-states',
                                                                                                       'united-states',
                                                                                       'canada, france, united-states',
                                                                                           'saint-pierre-and-miquelon',
                                                                                                              'canada',
                                                                                                    'french-polynesia',
                                                                                            'france, french-polynesia',
                                                                                    'democratic-republic-of-the-congo',
 ...
                                                                                                              'serbia',
                                                                                                            'botswana',
                                                                                                               'world',
                                                                                                            'maldives',
                                                                                                             'belarus',
                                                                                                               'macau',
                                                                                                  'australia, germany',
                                                                                                    'ireland, romania',
                                                                                               'china, united-kingdom',
 'argentina, bolivia, brazil, chile, guatemala, haiti, mexico, peru, united-states, venezuela, Latinoamérica, Mundial']
Length: 396, dtype: string

In [109]:
df.countries_tags.unique()

<ArrowStringArray>
[                                                                                                              'spain',
                                                                                                              'france',
                                                                                               'france, united-states',
                                                                                                       'united-states',
                                                                                       'canada, france, united-states',
                                                                                           'saint-pierre-and-miquelon',
                                                                                                              'canada',
                                                                                                    'french-polynesia',
                                                                                            'france, french-polynesia',
                                                                                    'democratic-republic-of-the-congo',
 ...
                                                                                                              'serbia',
                                                                                                            'botswana',
                                                                                                               'world',
                                                                                                            'maldives',
                                                                                                             'belarus',
                                                                                                               'macau',
                                                                                                  'australia, germany',
                                                                                                    'ireland, romania',
                                                                                               'china, united-kingdom',
 'argentina, bolivia, brazil, chile, guatemala, haiti, mexico, peru, united-states, venezuela, Latinoamérica, Mundial']
Length: 396, dtype: string

In [110]:
print(df['countries_tags'].head())

0                    spain
1                   france
2    france, united-states
3            united-states
4    france, united-states
Name: countries_tags, dtype: string

In [111]:
print(df.columns.tolist())

['code', 'product_name', 'brands', 'categories_tags', 'countries_tags', 'packaging_tags', 'stores', 'purchase_places', 'nutriscore_grade', 'nova_group', 'ecoscore_grade', 'ingredients_text', 'nutriments.sugars_100g', 'nutriments.energy-kcal_100g', 'nutriscore_grades', 'ecoscore_grades']

In [112]:
df['countries_tags'] = df['countries_tags'].apply(''.join)

In [113]:
df['countries_tags'] = df['countries_tags'].str.split(',')

In [114]:
print(type(df['countries_tags'].iloc[0]))

<class 'list'>

In [115]:
print(df['countries_tags'].head())

0                     [spain]
1                    [france]
2    [france,  united-states]
3             [united-states]
4    [france,  united-states]
Name: countries_tags, dtype: object

In [116]:
df = df.explode('countries_tags').reset_index(drop=True)

In [117]:
df['countries_tags'] = (
    df['countries_tags']
    .str.strip()
    .str.lower()
)

In [118]:
df['countries_tags'].unique()

<ArrowStringArray>
[                              'spain',                              'france',
                       'united-states',                              'canada',
           'saint-pierre-and-miquelon',                    'french-polynesia',
    'democratic-republic-of-the-congo',                      'united-kingdom',
                               'india',                             'unknown',
 ...
 'virgin-islands-of-the-united-states',                               'egypt',
                             'myanmar',                 'trinidad-and-tobago',
                            'botswana',                            'maldives',
                               'macau',                               'haiti',
                       'latinoamérica',                             'mundial']
Length: 148, dtype: str

In [119]:
df['packaging_tags'].unique()

<ArrowStringArray>
[                                                                                                                                                     '['unknown']',
                                                                                                                                            '['plastic', 'bottle']',
                                                                                                                                     '['bottle-or-vial', 'bottle']',
                                                                                                                                    '['aluminium-can', 'card-box']',
                                                                                                                             '['can', 'aluminium-can', 'aluminum']',
                                                                                                                                                      '['plastic']',
                                                                                                            '['plastic', 'bottle-or-vial', 'bottle', 'pet-bottle']',
                                                                                                                                               '['plastic-bottle']',
                                                                                                                                             '['plastic', 'fresh']',
                                                                                                                                                        '['brick']',
 ...
                '['plastic', 'pe-7-polyethylene', 'hdpe-2-high-density-polyethylene', 'pet-1-polyethylene-terephthalate', 'pp-5-polypropylene', 'pet-transparent']',
                                                                                                                                             '['plastic', 'paper']',
                                                                                                  '['plastic', 'pe-polyethylene', 'ldpe-low-density-polyethylene']',
                                                                                                                        '['plastic', 'pp-polypropylene', 'bottle']',
                              '['plastic', 'pe-polyethylene', 'hdpe-high-density-polyethylene', 'ldpe-low-density-polyethylene', 'pet-polyethylene-terephthalate']',
 '['plastic', 'recycled-material', 'pet-polyethylene-terephthalate', 'recycled-plastic', 'bottle', 'rpet-recycled-polyethylene-terephthalate', 'transparent-rpet']',
                                                                   '['plastic', 'bottle-or-vial', 'pet-1-polyethylene-terephthalate', 'bottle', 'pet-transparent']',
                                                                                                                                                         '['azul']',
                                                                                                                         '['boite-en-carton', 'film-en-plastique']',
                                                                                                                                                   '['tetra-pack']']
Length: 337, dtype: string

In [120]:
df = df.explode('packaging_tags').reset_index(drop=True)

In [121]:
df['packaging_tags'] = (
    df['packaging_tags']
    .str.strip()
    .str.lower()
)

In [122]:
df['packaging_tags'].value_counts().head(30)

packaging_tags
['unknown']                                                                                                                                                                                                                   4026
['plastic']                                                                                                                                                                                                                    302
['plastic', 'bottle']                                                                                                                                                                                                          147
['bottle']                                                                                                                                                                                                                      81
['can', 'drink-can']                                                                                                                                                                                                            58
['metal', 'recyclable-metals', 'aluminium', 'can', 'drink-can']                                                                                                                                                                 57
['can']                                                                                                                                                                                                                         53
['pet-bottle']                                                                                                                                                                                                                  45
['plastic', 'bottle-or-vial', 'bottle']                                                                                                                                                                                         41
['bouteille-plastique']                                                                                                                                                                                                         36
['aluminium-can']                                                                                                                                                                                                               36
['glass']                                                                                                                                                                                                                       35
['plastic', 'pet-polyethylene-terephthalate']                                                                                                                                                                                   33
['plastic', 'pe-7-polyethylene', 'bottle-or-vial', 'hdpe-2-high-density-polyethylene', 'pet-1-polyethylene-terephthalate', 'bottle', 'bouchon-en-plastique', 'it:bottiglia-pet', 'pt:pet-bottle', 'pt:pp-lid', 'pt:stuck']      31
['plastic-bottle']                                                                                                                                                                                                              29
['green-dot']                                                                                                                                                                                                                   27
['unknown-packaging']                                                                                                                                                                                                           27
['metal', 'recyclable-metals', 'aluminium']                                                                                                                                                                                     26
['tethered-cap', 'bouchon', 'bouchon-ou-couvercle', 'bouteille', 'bouteille-ou-flacon', 'pet-bottle', 'plastic-label', 'plastique']                                                                                             26
['plastic', 'bottle-or-vial', 'pet-1-polyethylene-terephthalate', 'bottle', 'pet-bottle']                                                                                                                                       26
['de:recycle-me-again-this-bottle-is-made-from-100-recycled-plastic']                                                                                                                                                           23
['metal', 'recyclable-metals', 'aluminium', 'can']                                                                                                                                                                              22
['it:bottiglia-pet']                                                                                                                                                                                                            21
['plastic', 'pet-polyethylene-terephthalate', 'bottle', 'transparent-pet']                                                                                                                                                      18
['plastic', 'pet-polyethylene-terephthalate', 'de:einwegpfand']                                                                                                                                                                 17
['plastic', 'pet-polyethylene-terephthalate', 'bottle']                                                                                                                                                                         16
['plastic', 'bottle-or-vial', 'pet-1-polyethylene-terephthalate', 'bottle', 'recyclable-material', 'recyclable-plastic']                                                                                                        15
['botella-de-plastico']                                                                                                                                                                                                         15
['multilayer-composite', 'tetra-pak', 'brick']                                                                                                                                                                                  15
['plastic', 'recycled-material', 'pet-polyethylene-terephthalate', 'recycled-plastic', 'bottle', 'rpet-recycled-polyethylene-terephthalate', 'transparent-pet', 'transparent-rpet']                                             15
Name: count, dtype: int64[pyarrow]

In [123]:
import ast

df['packaging_tags'] = df['packaging_tags'].apply(ast.literal_eval)
df = df.explode('packaging_tags').reset_index(drop=True)
df['packaging_tags'] = df['packaging_tags'].str.strip().str.lower()

In [124]:
df['packaging_tags'].unique()

<ArrowStringArray>
[                                                                   'unknown',
                                                                    'plastic',
                                                                     'bottle',
                                                             'bottle-or-vial',
                                                              'aluminium-can',
                                                                   'card-box',
                                                                        'can',
                                                                   'aluminum',
                                                                 'pet-bottle',
                                                             'plastic-bottle',
 ...
                                                         'paper-based-carton',
 'nl:161⁰-coke-com-2-pant-c-recycle-skal-resirkuleres-22-0066-gbnobe-t2ae10b',
                                                                  'coca-cola',
                                                              '1-plastic-lid',
                                                   'screw-lid-plastic-bottle',
                                                            'pet-transparent',
                                                                        'cun',
                                                         'pp-5-polypropylene',
                                                                       'azul',
                                                                 'tetra-pack']
Length: 276, dtype: str

In [125]:
noise_tags = [
    'unknown',
    'azul',
    'cun',
    'coca-cola',
    'nl:161⁰-coke-com-2-pant-c-recycle-skal-resirkuleres-22-0066-gbnobe-t2ae10b'
]

df = df[~df['packaging_tags'].isin(noise_tags)]

In [126]:
df['stores'].unique()

<ArrowStringArray>
[                                                                                                 '['unknown']',
                                                                                    '['walgreens', 'speedway']',
                                                                                                '['carrefour']',
                                                                                                  '['hyper u']',
                                                                 '['carrefour', 'hyper u', 'ls proxy', 'maxi']',
 '['real canadian superstore', "shopper's drug mart", 'walmart', 'safeway', 'shell', 'circle k', 'on the run']',
                                                               '['walmart', 'atlantic superstore', 'circle k']',
                                                                                                    '['tesco']',
                                                                                               '['restaurant']',
                                                                                               '["mcdonald's"]',
 ...
                                                    '['fsa', 'fidalga', 'multicenter', 'hipermaxi', 'agenbol']',
                              '['hipermaxi', 'mega licor', 'amarket', 'farmacorp', 'miniso', 'fsa', 'agenbol']',
                        '['ic norte', 'fidalga', 'farmacias chavez', 'farmacorp', 'ketal', 'farmacias zurich']',
                                                                                                   '['tigros']',
                                                                                                   '['frendo']',
                                        '['farmacorp', 'amarket', 'mercadon', 'multicenter', 'fsa', 'fidalga']',
                                                                  '['amarket', 'farmacorp', 'farmacia zurich']',
                                                                                                      '['fsa']',
                                                                                                 '['circle k']',
                                                                                  '['carrefour tom constanța']']
Length: 220, dtype: string

In [127]:
print(type(df['stores'].iloc[0]))

<class 'str'>

In [128]:
print(df['stores'].dtype)

string

In [129]:
df = df.explode('stores').reset_index(drop=True)

df['stores'] = df['stores'].str.strip().str.lower()

df['stores'].unique()

<ArrowStringArray>
[                                                                                                 '['unknown']',
                                                                                    '['walgreens', 'speedway']',
                                                                                                '['carrefour']',
                                                                                                  '['hyper u']',
                                                                 '['carrefour', 'hyper u', 'ls proxy', 'maxi']',
 '['real canadian superstore', "shopper's drug mart", 'walmart', 'safeway', 'shell', 'circle k', 'on the run']',
                                                               '['walmart', 'atlantic superstore', 'circle k']',
                                                                                                    '['tesco']',
                                                                                               '['restaurant']',
                                                                                               '["mcdonald's"]',
 ...
                                                    '['fsa', 'fidalga', 'multicenter', 'hipermaxi', 'agenbol']',
                              '['hipermaxi', 'mega licor', 'amarket', 'farmacorp', 'miniso', 'fsa', 'agenbol']',
                        '['ic norte', 'fidalga', 'farmacias chavez', 'farmacorp', 'ketal', 'farmacias zurich']',
                                                                                                   '['tigros']',
                                                                                                   '['frendo']',
                                        '['farmacorp', 'amarket', 'mercadon', 'multicenter', 'fsa', 'fidalga']',
                                                                  '['amarket', 'farmacorp', 'farmacia zurich']',
                                                                                                      '['fsa']',
                                                                                                 '['circle k']',
                                                                                  '['carrefour tom constanța']']
Length: 220, dtype: string

In [130]:
df.purchase_places.unique()

<ArrowStringArray>
[                                                       '['unknown']',
 '['san francisco', 'california', 'usa', 'grand rapids', 'michigan']',
                                                         '['canada']',
                                       '['saint pierre et miquelon']',
                                    '['arue', 'polynésie francaise']',
                         '['polynésie francaise', 'arue', 'papeete']',
                                            '['polynésie francaise']',
                       '['montréal', 'canada', 'calgary', 'alberta']',
                                   '['toronto', 'ontario', 'canada']',
                                                     '['california']',
 ...
                                                         '['brasil']',
                                                          '['suomi']',
                                                   '['magyarország']',
                                                  '['pori', 'suomi']',
                                               '['bergen', 'norway']',
                                                       '['pakistan']',
                                                      '['nederland']',
                                                         '['norway']',
                                                     '['bangladesh']',
                                       '['los angeles', 'ca', 'usa']']
Length: 166, dtype: string

In [131]:
df = df.explode('purchase_places').reset_index(drop=True)

df['purchase_places'] = df['purchase_places'].str.strip().str.lower()

df['purchase_places'].unique()

<ArrowStringArray>
[                                                       '['unknown']',
 '['san francisco', 'california', 'usa', 'grand rapids', 'michigan']',
                                                         '['canada']',
                                       '['saint pierre et miquelon']',
                                    '['arue', 'polynésie francaise']',
                         '['polynésie francaise', 'arue', 'papeete']',
                                            '['polynésie francaise']',
                       '['montréal', 'canada', 'calgary', 'alberta']',
                                   '['toronto', 'ontario', 'canada']',
                                                     '['california']',
 ...
                                                         '['brasil']',
                                                          '['suomi']',
                                                   '['magyarország']',
                                                  '['pori', 'suomi']',
                                               '['bergen', 'norway']',
                                                       '['pakistan']',
                                                      '['nederland']',
                                                         '['norway']',
                                                     '['bangladesh']',
                                       '['los angeles', 'ca', 'usa']']
Length: 166, dtype: string

In [132]:
df = df.explode('nutriscore_grade').reset_index(drop=True)

df['nutriscore_grade'] = df['nutriscore_grade'].str.strip().str.lower()

df['nutriscore_grade'].unique()

<ArrowStringArray>
[       '['unknown']',              '['e']',              '['c']',
              '['d']',              '['b']',              '['a']',
 '['not-applicable']']
Length: 7, dtype: string

In [133]:
df = df.explode('ecoscore_grade').reset_index(drop=True)

df['ecoscore_grade'] = df['ecoscore_grade'].str.strip().str.lower()

df['ecoscore_grade'].unique()

<ArrowStringArray>
[       '['unknown']', '['not-applicable']',              '['c']',
              '['e']',              '['a']',              '['d']',
         '['a-plus']']
Length: 7, dtype: string

In [134]:
df = df.explode('ingredients_text').reset_index(drop=True)

df['ingredients_text'] = df['ingredients_text'].str.strip().str.lower()

df['ingredients_text'].unique()

<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '['unknown']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '['carbonated water', 'cane sugar', 'caramel color', 'phosphoric acid', 'natural flavors', 'caffeine']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             '['pledse recycle cans', 'cartons cts ainer fructose corn syrup 1 can phosphoric acid', 'natural carbonated water', 'high caramel color', 'flavors', 'caffeine', '']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '['carbonated water', 'caramel color', 'phosphoric acid', 'aspartame', 'potassium benzoate (to protect taste)', 'natural flavors', 'potassium citrate', 'acesulfame potassium', 'caffeine.']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   '['carbonated water', 'caramel color', 'phosphoric acid', 'ašpartame', 'pótasshum benzoate (to protect tasté)', 'natural flavors', 'potassium citrate', 'acesulfame potassium', 'caffeine. caffeine content: 48 mg/16.9fl oz']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       '['carbonated water high fructose corn syrup caramel color phosphoric acid', 'natural flavors', 'caffeine caffeine content:34 mg/12fl oz']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '['carbonated water', 'cane sugar', 'caramel color', 'natural flavors', 'phosphoric acid', 'potassium benzoate', 'caffeine', 'stevia leaf extract']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       '['coffee (water', 'coffee)', 'milk', 'sugar', 'natural flavors', 'sodium bicarbonate', 'carrageenan', '']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '['filtered water', 'concentrated orange juice']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '['carbonated water', 'sugar', 'glucose-fructose', 'caramel colour', 'phosphoric acid', 'natural flavour', 'caffeine']',
 ...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '['apa', 'zahăr', 'dioxid de carbon', 'suc de lamaie verde din concentrat (0', '5%)', 'colorant e 150d', 'arome', 'aroma cafeina', 'acidifiant acid fosforic', 'corector de aciditate citrati de sodiu. a se consuma de preferintă înainte de: vezi pe ambalaj (primul rând']',
                                                                                                                                                                                                                                                              '['apă', 'suc de lămâie din concentrat (6%)', 'zahar', 'dioxid de carbon', 'acidifianti (acid malic', 'acid citric)', 'îndulcitori (acesulfam-k', 'aspartam', 'neohesperidină dc)', 'antioxidant (acid ascorbic)', 'corector de aciditate (citrati de sodiu)', 'conservant (sorbat de potasiu)', 'stabilizatori (e 414', 'e 445)', 'arome naturale de lămâie cu alte arome naturale', 'colorant (caroteni). conţine o sursă de fenilalanină. sedimente si schimbarea de culoare pot apărea în mod natural. acestea nu vor afecta calitatea rand).']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '['ingrediente apa', 'zahar', 'dioxid de carbon', 'colorant e150d acidifiant acid fosforic', 'arome naturale', 'aroma cafeina. ase consuma', 'de preferinta', 'inainte de: vezi pe ambalaj', 'pe gatul sticlei', 'al 2-a rand.']',
                                                                                                                                                                                                                                                                                                                                                                                                                           '['apă', 'zahăr', 'dioxid de carbon', 'acidifiant (acid citric)', 'arome naturale', 'concentrate din fructe si legume (cartofi dulci', 'mere', 'ridiche', 'cirese)', 'conservant (sorbat de potasiul indulcitori (zaharine', 'aspartam)', 'colorant (albastru strălucitor fcf contine o sursă de fenilalanină. a se consuma de preferinţă inainte de: vezi pe ambalaj (primul rând).']',
                                                                                                                                                                                                         '['apa', 'zahär', 'suc de fructe din lamaie 2%', 'zmeură 0', '1%)', 'dioxid de carbon', 'acidifiant facio ciuic)', 'aromă naturală de zmeură cu alte arome naturale', 'corectori de aciditate (citrați de sodiu', 'clorurà de magneziu). arome', 'concentrate din fructe si legume (morcovi', 'coacaze negrel', 'conservant (sorbat de potasiu)', 'indulcitori (aspartam', 'zaharine). contine o sursă de fenilalanină. sedimente si schimbarea de culoare pot aparea in mod natural. acestea nu vor afecta calitatea produsului a se consuma de preferinţă înainte de: vezi pe ambalaj (primul rand).']',
                                                                                                                                '['apă', 'suc de lămâie din concentrat (3%)', 'dioxid de carbon', 'acidifianţi: acid citric', 'acid malic', 'îndulcitori: ciclamati', 'acesulfam-k', 'sucraloză', 'glicozide steviolice din stevia', 'e 959', 'arome naturale de lămâie cu alte arome naturale', 'corector de aciditate: citrati de sodiu', 'conservant: sorbat de potasiu', 'stabilizatori: gumă de acacia', 'e 445', 'antioxidant: acid ascorbic', 'colorant: caroteni. acest produs poate suferi modificări de culoare si pot apărea sedimente. acestea sunt de origine naturală şi vă asigurăm că nu vor afecta calitatea produsului. a se consuma de preferință înainte de: vezi pe ambalaj (primul rând).']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      '['apa', 'radiant (acid citric', 'extract de ceai negru*** (0', '12%)', 'suc de lămâie 1%)', 'aroma naturalà de lamaie si lamaie verde cu alte arome naturale', 'corector de aciditate load antioxidant lacid ascorbic)', 'indulcitor (glicozide steviolice din stevia). a se consuma de preferinta in ambalaj (primul rand). ambalaj de unica folosinta.']',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   '['apă', 'sirop de fructoză', 'dioxid de carbon colorant e150d', 'acidifiant acid fosforic', 'arome naturale', 'aromă cafeină. a se consuma', 'de preferință', 'înainte de: vezi pe ambalaj.']',
 '['bautura racoritoare carbogazoasă cu gust de mere şi cirese', 'cu zahar si indulcitori. ingrediente: apă', 'zahăr', 'suc de lamaie din concentrat (1%)', 'dioxid de carbon', 'acidifianți (acid malic', 'acid citric)', 'concentrate din fructe si legume (morcovi', 'coacăze negre)', 'colorant (e 150d)', 'arome naturale', 'indulcitori (ciclamați', 'acesulfam-k', 'sucraloză)', 'conservant (sorbat de potasiu)', 'corector de aciditate (citrați de sodiu). acest produs poate suferi modificări de culoare şi pot apărea sedimente. acestea sunt de origine naturală si vă asigurăm că nu vor afecta calitatea produsului. a se consuma de preferintă înainte de: vezi pe ambalaj (primul rând]. a se pastra la loc răcoros', 'ferit de soare. ambalaj de unică folosinţă. 2026 the coca-cola company']',
                                                                                                                                                                                '['apă', 'zahăr', 'suc de visine din concentrat (1', '3% acidifiant (acid malic)', 'dioxid de carbon', 'concentrate din fructe si legume (morcovi', 'coacăze negre)', 'aromă naturală de piper negru cu alte arome naturale', 'conservant (sorbat de potasiul indulcitori (acesulfam-k', 'sucraloză). a se consuma de preferinţă înainte de: vezi pe ambalaj (primul rând). a se pastra la loc răcoros', 'ferit de soare. schimbarea culorii poate aparea in mod natural', 'insă calitatea produsului nu va fi afectată ambalaj de unica folosintä. produs cu autorizarea schweppes holdings ltd. 2026 european refreshments uc']']
Length: 902, dtype: string

In [135]:
df.ingredients_text.str.split(',')

0                                           [['unknown']]
1                                           [['unknown']]
2       [['carbonated water',  'cane sugar',  'caramel...
3       [['carbonated water',  'cane sugar',  'caramel...
4       [['carbonated water',  'cane sugar',  'caramel...
                              ...
4826    [['apă',  'sirop de fructoză',  'dioxid de car...
4827                                        [['unknown']]
4828    [['bautura racoritoare carbogazoasă cu gust de...
4829    [['apă',  'zahăr',  'suc de visine din concent...
4830                                        [['unknown']]
Name: ingredients_text, Length: 4831, dtype: object

In [136]:
df['ingredients_text'] = df['ingredients_text'].apply(ast.literal_eval)

In [137]:
df = df.explode('ingredients_text').reset_index(drop=True)

In [138]:
df['ingredients_text'] = (
    df['ingredients_text']
    .str.strip()
    .str.lower()
)

In [139]:
print(df['ingredients_text'].unique())

<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                   'unknown',
                                                                                                                                                                                                                                                                                           'carbonated water',
                                                                                                                                                                                                                                                                                                 'cane sugar',
                                                                                                                                                                                                                                                                                              'caramel color',
                                                                                                                                                                                                                                                                                            'phosphoric acid',
                                                                                                                                                                                                                                                                                            'natural flavors',
                                                                                                                                                                                                                                                                                                   'caffeine',
                                                                                                                                                                                                                                                                                        'pledse recycle cans',
                                                                                                                                                                                                                                                'cartons cts ainer fructose corn syrup 1 can phosphoric acid',
                                                                                                                                                                                                                                                                                   'natural carbonated water',
 ...
                                                                                                                                                                                                                                                                                     'indulcitori (ciclamați',
 'corector de aciditate (citrați de sodiu). acest produs poate suferi modificări de culoare şi pot apărea sedimente. acestea sunt de origine naturală si vă asigurăm că nu vor afecta calitatea produsului. a se consuma de preferintă înainte de: vezi pe ambalaj (primul rând]. a se pastra la loc răcoros',
                                                                                                                                                                                                                                     'ferit de soare. ambalaj de unică folosinţă. 2026 the coca-cola company',
                                                                                                                                                                                                                                                                            'suc de visine din concentrat (1',
                                                                                                                                                                                                                                                                                 '3% acidifiant (acid malic)',
                                                                                                                                                                                                                                                       'aromă naturală de piper negru cu alte arome naturale',
                                                                                                                                                                                                                                                    'conservant (sorbat de potasiul indulcitori (acesulfam-k',
                                                                                                                                                                                               'sucraloză). a se consuma de preferinţă înainte de: vezi pe ambalaj (primul rând). a se pastra la loc răcoros',
                                                                                                                                                                                                                                             'ferit de soare. schimbarea culorii poate aparea in mod natural',
                                                                                                                                                        'insă calitatea produsului nu va fi afectată ambalaj de unica folosintä. produs cu autorizarea schweppes holdings ltd. 2026 european refreshments uc']
Length: 3328, dtype: str

In [140]:
rare = df['ingredients_text'].value_counts()

rare[rare == 1]

ingredients_text
filtered water                                                                                                                                         1
concentrated orange juice                                                                                                                              1
acidifiant : (e330                                                                                                                                     1
conservateur : (e202)                                                                                                                                  1
antioxydant : (e300)                                                                                                                                   1
                                                                                                                                                      ..
aromă naturală de piper negru cu alte arome naturale                                                                                                   1
conservant (sorbat de potasiul indulcitori (acesulfam-k                                                                                                1
sucraloză). a se consuma de preferinţă înainte de: vezi pe ambalaj (primul rând). a se pastra la loc răcoros                                           1
ferit de soare. schimbarea culorii poate aparea in mod natural                                                                                         1
insă calitatea produsului nu va fi afectată ambalaj de unica folosintä. produs cu autorizarea schweppes holdings ltd. 2026 european refreshments uc    1
Name: count, Length: 962, dtype: int64

In [141]:
df['countries_tags'].value_counts().head(10)

countries_tags
france            6043
germany           3385
bolivia           2216
spain             1981
belgium           1803
italy             1460
switzerland       1312
united-kingdom    1307
romania           1037
sweden            1027
Name: count, dtype: int64

In [142]:
df['purchase_places'].value_counts().head(20)

purchase_places
['unknown']                                              21665
['cochabamba', 'bolivia']                                 1632
['bolivia']                                               1136
['france']                                                 749
['deutschland']                                            514
['netherlands', 'france', 'italy']                         432
['sverige', 'sweden']                                      387
['belgique', 'ireland', 'dublin']                          385
['españa']                                                 354
['switzerland']                                            342
['calgary', 'alberta', 'canada']                           306
['italia']                                                 271
['walmart']                                                243
['polska']                                                 236
['courrières', 'france']                                   211
['danemark']                                               196
['france', 'nice']                                         196
['liverpool', 'united kingdom', 'france', 'hrvatska']      180
['sweden']                                                 178
['romania']                                                178
Name: count, dtype: int64[pyarrow]

In [143]:
df['stores'].value_counts().head(20)

stores
['unknown']                                                                                                                    23374
['farmacorp']                                                                                                                    503
['albert heijn', 'carrefour', 'decò', 'carrefour.fr']                                                                            432
['farmacorp', 'fidalga', 'amarket']                                                                                              399
['spar', 'centra', 'carrefour.fr']                                                                                               385
['city gross']                                                                                                                   379
['carrefour']                                                                                                                    367
['condis', 'amazon']                                                                                                             272
['rewe', 'netto']                                                                                                                270
['mercadona']                                                                                                                    243
['auchan']                                                                                                                       222
['asda']                                                                                                                         218
['intermarché', 'casino', 'e.leclerc', 'auchan', 'carrefour market', 'carrefour city', 'carrefour express', 'aldi', 'lidl']      196
['edeka']                                                                                                                        183
['globus']                                                                                                                       182
['delhaize']                                                                                                                     178
['la doi pasi']                                                                                                                  150
['cora', 'norma']                                                                                                                147
['pressbyrån']                                                                                                                   144
['coop']                                                                                                                         134
Name: count, dtype: int64[pyarrow]

In [144]:
print(len(df['countries_tags']))
print(len(df['nutriscore_grade']))

34655
34655

In [145]:
print(df[['countries_tags', 'nutriscore_grade']].shape)

(34655, 2)

In [146]:
print(df['countries_tags'].dtype)
print(df['nutriscore_grade'].dtype)

str
string

In [147]:
df.dtypes

code                           float64
product_name                    string
brands                             str
categories_tags                 string
countries_tags                     str
packaging_tags                     str
stores                          string
purchase_places                 string
nutriscore_grade                string
nova_group                     float64
ecoscore_grade                  string
ingredients_text                   str
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
nutriscore_grades               string
ecoscore_grades                 string
dtype: object

In [148]:
cat_cols = df.select_dtypes(include=['object', 'string']).columns
for col in cat_cols:
    df[col] = df[col].astype(str)

In [149]:
df.dtypes

code                           float64
product_name                       str
brands                             str
categories_tags                    str
countries_tags                     str
packaging_tags                     str
stores                             str
purchase_places                    str
nutriscore_grade                   str
nova_group                     float64
ecoscore_grade                     str
ingredients_text                   str
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
nutriscore_grades                  str
ecoscore_grades                    str
dtype: object

In [150]:
df['nutriscore_grade'] = df['nutriscore_grade'].str.split(',')

In [151]:
df

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g,nutriscore_grades,ecoscore_grades
0,4.211156e+10,['coca-cola zéro'],"['coca-cola-light', 'coca-cola']","beverages, carbonated-drinks, artificially-swe...",france,plastic,['unknown'],['unknown'],[['unknown']],NaN,['unknown'],unknown,NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
1,4.211156e+10,['coca-cola zéro'],"['coca-cola-light', 'coca-cola']","beverages, carbonated-drinks, artificially-swe...",france,bottle,['unknown'],['unknown'],[['unknown']],NaN,['unknown'],unknown,NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
2,4.900000e+10,['coca-cola'],['coca-cola'],"beverages-and-beverages-preparations, beverage...",france,bottle-or-vial,['unknown'],['unknown'],[['e']],4.0,['unknown'],carbonated water,NaN,NaN,['e'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
3,4.900000e+10,['coca-cola'],['coca-cola'],"beverages-and-beverages-preparations, beverage...",france,bottle-or-vial,['unknown'],['unknown'],[['e']],4.0,['unknown'],cane sugar,NaN,NaN,['e'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
4,4.900000e+10,['coca-cola'],['coca-cola'],"beverages-and-beverages-preparations, beverage...",france,bottle-or-vial,['unknown'],['unknown'],[['e']],4.0,['unknown'],caramel color,NaN,NaN,['e'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34650,5.942321e+12,['schweppes vișine și piper negru'],['coca-cola'],"beverages-and-beverages-preparations, beverage...",romania,plastic,['unknown'],['unknown'],[['d']],4.0,['unknown'],conservant (sorbat de potasiul indulcitori (ac...,NaN,NaN,['d'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
34651,5.942321e+12,['schweppes vișine și piper negru'],['coca-cola'],"beverages-and-beverages-preparations, beverage...",romania,plastic,['unknown'],['unknown'],[['d']],4.0,['unknown'],sucraloză). a se consuma de preferinţă înainte...,NaN,NaN,['d'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
34652,5.942321e+12,['schweppes vișine și piper negru'],['coca-cola'],"beverages-and-beverages-preparations, beverage...",romania,plastic,['unknown'],['unknown'],[['d']],4.0,['unknown'],ferit de soare. schimbarea culorii poate apare...,NaN,NaN,['d'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
34653,5.942321e+12,['schweppes vișine și piper negru'],['coca-cola'],"beverages-and-beverages-preparations, beverage...",romania,plastic,['unknown'],['unknown'],[['d']],4.0,['unknown'],insă calitatea produsului nu va fi afectată am...,NaN,NaN,['d'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"
34654,5.449000e+12,['original taste'],['coca-cola'],unknown,austria,tetra-pack,['unknown'],['unknown'],[['unknown']],NaN,['unknown'],unknown,NaN,NaN,['unknown'],"['u', 'n', 'k', 'n', 'o', 'w', 'n']"