In [1]:
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("datasets/topo chico_from_dump.csv")
df

,code,product_name,brands,categories_tags,countries_tags,packaging_tags,stores,purchase_places,nutriscore_grade,nova_group,ecoscore_grade,ingredients_text,nutriments.sugars_100g,nutriments.energy-kcal_100g
0,21136010374,MINERAL WATER CARBONATED,Topo Chico,undefined,united-states,"bottle-or-vial, bottle, glass-bottle",NaN,NaN,a,NaN,NaN,CARBONATED MINERAL WATER BOTTLED ONLY AT SOURCE.,NaN,NaN
1,21136010480,Agua Mineral,Cia. Topo Chico S.A.,"beverages-and-beverages-preparations, beverage...","mexico, united-states",NaN,NaN,NaN,a,4.0,NaN,MINERAL WATER AND CARBON DIOXIDE.,NaN,NaN
2,21136010626,"Topo Chico, Sparkling Carbonatada Agua Mineral...",Cia. Topo Chico S.A.,"beverages, waters",united-states,NaN,NaN,NaN,unknown,4.0,NaN,"Mineral water, carbon dioxide.",NaN,NaN
3,21136011500,Soda,Cia. Topo Chico S.A.,"beverages, carbonated-drinks, sodas",united-states,NaN,NaN,NaN,e,4.0,not-applicable,"Carbonated water, cane sugar, artificial and n...",10.99,42.0
4,21136011579,"Topo Chico, Carbonated Beverage, Apple",Cia. Topo Chico S.A.,"beverages, carbonated-drinks, sodas",united-states,NaN,NaN,NaN,e,4.0,not-applicable,"Carbonated water, cane sugar, citric acid, car...",12.24,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,993350000724,Topo chico,NaN,NaN,mexico,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
77,810078782193,Margarita Flavored Alcohol Beverage,Topo Chico,NaN,united-states,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
78,721136000480,Topo chico 1.5L,NaN,NaN,mexico,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
79,1219258,Raspberry with Lemon Flavored Sparkling Water,Topo Chico Sabores,NaN,united-states,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
80,810078782186,Margarita Flavored Alcohol Beverage Prickly Pear,Topo Chico,NaN,united-states,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN

In [3]:
df.dtypes

code                            object
product_name                       str
brands                             str
categories_tags                    str
countries_tags                     str
packaging_tags                     str
stores                             str
purchase_places                    str
nutriscore_grade                   str
nova_group                     float64
ecoscore_grade                     str
ingredients_text                   str
nutriments.sugars_100g         float64
nutriments.energy-kcal_100g    float64
dtype: object

In [4]:
df.code.unique()

array([21136010374, 21136010480, 21136010626, 21136011500, 21136011579,
       21136013504, 21136013573, 21136014501, 21136015508, 21136016185,
       21136019506, 21136019575, 21136020373, 21136050462, 21136110180,
       21136120448, 21136414370, 21136616507, 21136010541, 21136010534,
       5449000294722, 5449000294746, 21136180619, 5449000294708,
       21136180657, 21136010350, 21136180794, 21136016444, 5000112650150,
       21136180800, 5449000300904, 21136180817, 21136180558, 21136180954,
       21136180701, 21136180664, 810078780014, 2004361007713,
       91055901860836515341, 21136180596, 21136180626, 21136010121,
       810078780045, 810078780342, 21136180947, 810078780021, 21136181166,
       5000112650167, 21136110449, 810078780564, 810078781035,
       7894900335040, 7894900335095, 7894900335026, 7501055379866,
       628068270380, 21136181371, 4774537447244, 21266181371, 21136181678,
       21136181708, 3118153, 21266010541, 21136181616, 2113618136,
       21136181623, 783474362125, 21136181685, 7501055387007, 2113601054,
       810078782223, 21136181463, 810078781356, 17386922, 810078781370,
       21136181715, 993350000724, 810078782193, 721136000480, 1219258,
       810078782186], dtype=object)

In [7]:
df=df.astype({"code": "int64"})

In [8]:
df.brands.unique()

<ArrowStringArray>
[           'Topo Chico', 'Cia. Topo Chico  S.A.',                     nan,
     'Coca-Cola Company',            'Topo chico',            'topo chico',
             'Too Chico',            'TOPO CHICO',    'Topo Chico Sabores',
       'Topo Chico Hard']
Length: 10, dtype: str

In [9]:
df.brands = df.brands.replace({
    "Topo chico": "Topo Chico",
    "topo chico": "Topo Chico",
    "TOPO CHICO": "Topo Chico",
    "Too Chico": "Topo Chico"
}, regex=True)

In [10]:
df.brands = df.brands.fillna("unknown")
df.brands.isnull().sum()

np.int64(0)

In [11]:
cols = [
    "categories_tags",
    "countries_tags",
    "packaging_tags",
    "stores",
    "purchase_places",
    "ecoscore_grade",
    "ingredients_text"
]

df[cols] = df[cols].fillna("Unknown")

In [12]:
df_clean = df.copy()

In [13]:
country_df = df_clean.copy()
country_df["countries_tags"] = country_df["countries_tags"].str.split(",")
country_df = country_df.explode("countries_tags")
country_df["countries_tags"] = country_df["countries_tags"].str.strip().str.lower()

In [14]:
pack_df = df_clean.copy()
pack_df["packaging_tags"] = pack_df["packaging_tags"].str.split(",")
pack_df = pack_df.explode("packaging_tags")
pack_df["packaging_tags"] = pack_df["packaging_tags"].str.strip().str.lower()

In [15]:
cat_df = df_clean.copy()
cat_df["categories_tags"] = cat_df["categories_tags"].str.split(",")
cat_df = cat_df.explode("categories_tags")
cat_df["categories_tags"] = cat_df["categories_tags"].str.strip().str.lower()

In [16]:
store_df = df_clean.copy()
store_df["stores"] = store_df["stores"].str.split(",")
store_df = store_df.explode("stores")
store_df["stores"] = store_df["stores"].str.strip().str.lower()

In [17]:
products_df = df_clean.copy()
products_df["product_name"] = products_df["product_name"].str.split(",")
products_df = products_df.explode("product_name")
products_df["product_name"] = products_df["product_name"].str.strip().str.lower()

In [18]:
df.brands.value_counts()

brands
Topo Chico               44
unknown                  16
Cia. Topo Chico  S.A.    15
Topo Chico Sabores        4
Coca-Cola Company         1
Topo Chico Hard           1
Name: count, dtype: int64

In [19]:
country_df.value_counts("countries_tags")

countries_tags
united-states    60
spain             6
mexico            5
brazil            3
luxembourg        2
germany           2
unknown           1
france            1
italy             1
saudi-arabia      1
japan             1
Name: count, dtype: int64

In [20]:
pack_df.value_counts("packaging_tags")

packaging_tags
unknown                          72
bottle                            5
metal                             3
recyclable-metals                 3
aluminium                         3
bottle-or-vial                    1
glass-bottle                      1
pet-desechable-con-taparrosca     1
de:al                             1
Name: count, dtype: int64

In [21]:
cat_df.value_counts("categories_tags")

categories_tags
beverages                               44
unknown                                 34
beverages-and-beverages-preparations    22
waters                                  20
carbonated-drinks                       15
alcoholic-beverages                     13
carbonated-waters                        8
spring-waters                            7
mineral-waters                           7
sodas                                    7
hard-seltzer                             4
undefined                                3
carbonated-mineral-waters                2
hard-seltzers                            2
premixed-alcoholic-beverages             2
vodka-based-alcoholic-beverages          2
wines                                    1
de:alcopop                               1
de:alkoholhaltiges-mischgetränk          1
de:alkopop                               1
de:hard-seltzer                          1
de:premixgetränk                         1
de:ready-to-drink                        1
de:selt                                  1
de:wein                                  1
Name: count, dtype: int64

In [22]:
store_df.value_counts("stores")

stores
unknown         77
carrefour.fr     2
la plancha       1
méxico           1
soriana          1
abarrotes        1
chedraui         1
walmart          1
sam's            1
hagebaumarkt     1
Name: count, dtype: int64

In [23]:
products_df.value_counts("product_name")

product_name
topo chico                                          15
topo chico hard seltzer                              5
carbonated beverage                                  3
topo sabores                                         3
strawberry                                           3
                                                    ..
lime with mint extract filtered sparkling water      1
hard seltzer: oasis cherry                           1
margarita flavored alcohol beverage                  1
topo chico 1.5l                                      1
margarita flavored alcohol beverage prickly pear     1
Name: count, Length: 62, dtype: int64

In [24]:
print("Total Products :", products_df["product_name"].nunique())

Total Products : 62

In [25]:
print("Total Brands :", df["brands"].nunique())

Total Brands : 6

In [26]:
print("Total Categories :", cat_df["categories_tags"].nunique())

Total Categories : 25

In [27]:
print("Total Countries :", country_df["countries_tags"].nunique())

Total Countries : 11

In [28]:
print("Total Packaging Types :", pack_df["packaging_tags"].nunique())

Total Packaging Types : 9

In [29]:
print("Total Stores :", store_df["stores"].nunique())

Total Stores : 10

In [30]:
summary = pd.DataFrame({
    "Unique Values": df.nunique(),
    "Missing Values": df.isnull().sum(),
    "Data Type": df.dtypes
})

summary

                             Unique Values  Missing Values Data Type
code                                    81               0     int64
product_name                            65               0       str
brands                                   6               0       str
categories_tags                         18               0       str
countries_tags                          13               0       str
packaging_tags                           6               0       str
stores                                   4               0       str
purchase_places                          2               0       str
nutriscore_grade                         6               0       str
nova_group                               2              43   float64
ecoscore_grade                           3               0       str
ingredients_text                        39               0       str
nutriments.sugars_100g                  19              43   float64
nutriments.energy-kcal_100g             19              35   float64